// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- tf2_msgs__srv__FrameGraph_Request ----
base class tf2_msgs__srv__FrameGraph_Request extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class tf2_msgs__srv__FrameGraph_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__srv__FrameGraph_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsFrameGraph_Request extends BaseRosMessage<tf2_msgs__srv__FrameGraph_Request> {
  @override
  String get typeName => 'FrameGraph_Request';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsFrameGraph_Request() {
    data = calloc<tf2_msgs__srv__FrameGraph_Request>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}

// ---- tf2_msgs__srv__FrameGraph_Response ----
base class tf2_msgs__srv__FrameGraph_Response extends ffi.Struct {
  external rosidl_runtime_c__String frame_yaml;
}

final class tf2_msgs__srv__FrameGraph_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__srv__FrameGraph_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsFrameGraph_Response extends BaseRosMessage<tf2_msgs__srv__FrameGraph_Response> {
  @override
  String get typeName => 'FrameGraph_Response';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsFrameGraph_Response() {
    data = calloc<tf2_msgs__srv__FrameGraph_Response>();
    frameYaml = '';
  }

  String get frameYaml {
    final s = data.ref.frame_yaml;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set frameYaml(String val) {
    final b = val.toNativeUtf8();
    data.ref.frame_yaml.data = b.cast<ffi.Char>();
    data.ref.frame_yaml.size = b.length;
    data.ref.frame_yaml.capacity = b.length + 1;
  }
}

// ---- Tf2MsgsFrameGraph (service) ----
class Tf2MsgsFrameGraph
    extends BaseRosService<Tf2MsgsFrameGraph_Request, Tf2MsgsFrameGraph_Response> {
  @override
  String get typeName => 'FrameGraph';
  @override
  String get packageName => 'tf2_msgs';

  @override
  Tf2MsgsFrameGraph_Request createRequest() => Tf2MsgsFrameGraph_Request();

  @override
  Tf2MsgsFrameGraph_Response createResponse() => Tf2MsgsFrameGraph_Response();
}
