// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'tf2_error.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;

// ---- tf2_msgs__action__LookupTransform_Goal ----
base class tf2_msgs__action__LookupTransform_Goal extends ffi.Struct {
  external rosidl_runtime_c__String target_frame;
  external rosidl_runtime_c__String source_frame;
  external builtin_interfaces__msg__Time source_time;
  external builtin_interfaces__msg__Duration timeout;
  external builtin_interfaces__msg__Time target_time;
  external rosidl_runtime_c__String fixed_frame;
  @ffi.Bool()
  external bool advanced;
}

final class tf2_msgs__action__LookupTransform_Goal__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__action__LookupTransform_Goal> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsLookupTransform_Goal extends BaseRosMessage<tf2_msgs__action__LookupTransform_Goal> {
  @override
  String get typeName => 'LookupTransform_Goal';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsLookupTransform_Goal() {
    data = calloc<tf2_msgs__action__LookupTransform_Goal>();
    targetFrame = '';
    sourceFrame = '';
    fixedFrame = '';
  }

  String get targetFrame {
    final s = data.ref.target_frame;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set targetFrame(String val) {
    final b = val.toNativeUtf8();
    data.ref.target_frame.data = b.cast<ffi.Char>();
    data.ref.target_frame.size = b.length;
    data.ref.target_frame.capacity = b.length + 1;
  }
  String get sourceFrame {
    final s = data.ref.source_frame;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set sourceFrame(String val) {
    final b = val.toNativeUtf8();
    data.ref.source_frame.data = b.cast<ffi.Char>();
    data.ref.source_frame.size = b.length;
    data.ref.source_frame.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'source_time' not generated;
  // reach the field directly via `data.ref.source_time`.
  // TODO(dart-gen): high-level accessor for 'timeout' not generated;
  // reach the field directly via `data.ref.timeout`.
  // TODO(dart-gen): high-level accessor for 'target_time' not generated;
  // reach the field directly via `data.ref.target_time`.
  String get fixedFrame {
    final s = data.ref.fixed_frame;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set fixedFrame(String val) {
    final b = val.toNativeUtf8();
    data.ref.fixed_frame.data = b.cast<ffi.Char>();
    data.ref.fixed_frame.size = b.length;
    data.ref.fixed_frame.capacity = b.length + 1;
  }
  bool get advanced =>
      data.ref.advanced;
  set advanced(bool val) =>
      data.ref.advanced = val;
}

// ---- tf2_msgs__action__LookupTransform_Result ----
base class tf2_msgs__action__LookupTransform_Result extends ffi.Struct {
  external geometry_msgs__msg__TransformStamped transform;
  external tf2_msgs__msg__TF2Error error;
}

final class tf2_msgs__action__LookupTransform_Result__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__action__LookupTransform_Result> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsLookupTransform_Result extends BaseRosMessage<tf2_msgs__action__LookupTransform_Result> {
  @override
  String get typeName => 'LookupTransform_Result';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsLookupTransform_Result() {
    data = calloc<tf2_msgs__action__LookupTransform_Result>();
  }

  // TODO(dart-gen): high-level accessor for 'transform' not generated;
  // reach the field directly via `data.ref.transform`.
  // TODO(dart-gen): high-level accessor for 'error' not generated;
  // reach the field directly via `data.ref.error`.
}

// ---- tf2_msgs__action__LookupTransform_Feedback ----
base class tf2_msgs__action__LookupTransform_Feedback extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class tf2_msgs__action__LookupTransform_Feedback__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__action__LookupTransform_Feedback> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsLookupTransform_Feedback extends BaseRosMessage<tf2_msgs__action__LookupTransform_Feedback> {
  @override
  String get typeName => 'LookupTransform_Feedback';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsLookupTransform_Feedback() {
    data = calloc<tf2_msgs__action__LookupTransform_Feedback>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}

// ---- Tf2MsgsLookupTransform (action) ----
class Tf2MsgsLookupTransform
    extends BaseRosAction<Tf2MsgsLookupTransform_Goal, Tf2MsgsLookupTransform_Result, Tf2MsgsLookupTransform_Feedback> {
  @override
  String get typeName => 'LookupTransform';
  @override
  String get packageName => 'tf2_msgs';

  @override
  Tf2MsgsLookupTransform_Goal createGoal() => Tf2MsgsLookupTransform_Goal();

  @override
  Tf2MsgsLookupTransform_Result createResult() => Tf2MsgsLookupTransform_Result();

  @override
  Tf2MsgsLookupTransform_Feedback createFeedback() => Tf2MsgsLookupTransform_Feedback();
}
