// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- tf2_msgs__msg__TF2Error ----
base class tf2_msgs__msg__TF2Error extends ffi.Struct {
  @ffi.Uint8()
  external int error;
  external rosidl_runtime_c__String error_string;
}

final class tf2_msgs__msg__TF2Error__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__msg__TF2Error> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsTF2Error extends BaseRosMessage<tf2_msgs__msg__TF2Error> {
  @override
  String get typeName => 'TF2Error';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsTF2Error() {
    data = calloc<tf2_msgs__msg__TF2Error>();
    errorString = '';
  }

  static const int NO_ERROR =
      0;
  static const int LOOKUP_ERROR =
      1;
  static const int CONNECTIVITY_ERROR =
      2;
  static const int EXTRAPOLATION_ERROR =
      3;
  static const int INVALID_ARGUMENT_ERROR =
      4;
  static const int TIMEOUT_ERROR =
      5;
  static const int TRANSFORM_ERROR =
      6;
  int get error =>
      data.ref.error;
  set error(int val) =>
      data.ref.error = val;
  String get errorString {
    final s = data.ref.error_string;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set errorString(String val) {
    final b = val.toNativeUtf8();
    data.ref.error_string.data = b.cast<ffi.Char>();
    data.ref.error_string.size = b.length;
    data.ref.error_string.capacity = b.length + 1;
  }
}
