// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:geometry_msgs/geometry_msgs.dart';

// ---- tf2_msgs__msg__TFMessage ----
base class tf2_msgs__msg__TFMessage extends ffi.Struct {
  external geometry_msgs__msg__TransformStamped__Sequence transforms;
}

final class tf2_msgs__msg__TFMessage__Sequence extends ffi.Struct {
  external ffi.Pointer<tf2_msgs__msg__TFMessage> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class Tf2MsgsTFMessage extends BaseRosMessage<tf2_msgs__msg__TFMessage> {
  @override
  String get typeName => 'TFMessage';
  @override
  String get packageName => 'tf2_msgs';

  Tf2MsgsTFMessage() {
    data = calloc<tf2_msgs__msg__TFMessage>();
  }

  // TODO(dart-gen): high-level accessor for 'transforms' not generated;
  // reach the field directly via `data.ref.transforms`.
}
