// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- rcl_interfaces__msg__FloatingPointRange ----
base class rcl_interfaces__msg__FloatingPointRange extends ffi.Struct {
  @ffi.Double()
  external double from_value;
  @ffi.Double()
  external double to_value;
  @ffi.Double()
  external double step;
}

final class rcl_interfaces__msg__FloatingPointRange__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__FloatingPointRange> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesFloatingPointRange extends BaseRosMessage<rcl_interfaces__msg__FloatingPointRange> {
  @override
  String get typeName => 'FloatingPointRange';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesFloatingPointRange() {
    data = calloc<rcl_interfaces__msg__FloatingPointRange>();
  }

  double get fromValue =>
      data.ref.from_value;
  set fromValue(double val) =>
      data.ref.from_value = val;
  double get toValue =>
      data.ref.to_value;
  set toValue(double val) =>
      data.ref.to_value = val;
  double get step =>
      data.ref.step;
  set step(double val) =>
      data.ref.step = val;
}
