// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'parameter_value.dart';

// ---- rcl_interfaces__srv__GetParameters_Request ----
base class rcl_interfaces__srv__GetParameters_Request extends ffi.Struct {
  external rosidl_runtime_c__String__Sequence names;
}

final class rcl_interfaces__srv__GetParameters_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__GetParameters_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesGetParameters_Request extends BaseRosMessage<rcl_interfaces__srv__GetParameters_Request> {
  @override
  String get typeName => 'GetParameters_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesGetParameters_Request() {
    data = calloc<rcl_interfaces__srv__GetParameters_Request>();
  }

  List<String> get names {
    final s = data.ref.names;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set names(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.names.data = a;
    data.ref.names.size = value.length;
    data.ref.names.capacity = value.length;
  }
}

// ---- rcl_interfaces__srv__GetParameters_Response ----
base class rcl_interfaces__srv__GetParameters_Response extends ffi.Struct {
  external rcl_interfaces__msg__ParameterValue__Sequence values;
}

final class rcl_interfaces__srv__GetParameters_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__GetParameters_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesGetParameters_Response extends BaseRosMessage<rcl_interfaces__srv__GetParameters_Response> {
  @override
  String get typeName => 'GetParameters_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesGetParameters_Response() {
    data = calloc<rcl_interfaces__srv__GetParameters_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'values' not generated;
  // reach the field directly via `data.ref.values`.
}

// ---- RclInterfacesGetParameters (service) ----
class RclInterfacesGetParameters
    extends BaseRosService<RclInterfacesGetParameters_Request, RclInterfacesGetParameters_Response> {
  @override
  String get typeName => 'GetParameters';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesGetParameters_Request createRequest() => RclInterfacesGetParameters_Request();

  @override
  RclInterfacesGetParameters_Response createResponse() => RclInterfacesGetParameters_Response();
}
