// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- rcl_interfaces__srv__GetParameterTypes_Request ----
base class rcl_interfaces__srv__GetParameterTypes_Request extends ffi.Struct {
  external rosidl_runtime_c__String__Sequence names;
}

final class rcl_interfaces__srv__GetParameterTypes_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__GetParameterTypes_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesGetParameterTypes_Request extends BaseRosMessage<rcl_interfaces__srv__GetParameterTypes_Request> {
  @override
  String get typeName => 'GetParameterTypes_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesGetParameterTypes_Request() {
    data = calloc<rcl_interfaces__srv__GetParameterTypes_Request>();
  }

  List<String> get names {
    final s = data.ref.names;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set names(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.names.data = a;
    data.ref.names.size = value.length;
    data.ref.names.capacity = value.length;
  }
}

// ---- rcl_interfaces__srv__GetParameterTypes_Response ----
base class rcl_interfaces__srv__GetParameterTypes_Response extends ffi.Struct {
  external rosidl_runtime_c__uint8__Sequence types;
}

final class rcl_interfaces__srv__GetParameterTypes_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__GetParameterTypes_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesGetParameterTypes_Response extends BaseRosMessage<rcl_interfaces__srv__GetParameterTypes_Response> {
  @override
  String get typeName => 'GetParameterTypes_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesGetParameterTypes_Response() {
    data = calloc<rcl_interfaces__srv__GetParameterTypes_Response>();
  }

  List<int> get types {
    final s = data.ref.types;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set types(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.types.data = a;
    data.ref.types.size = value.length;
    data.ref.types.capacity = value.length;
  }
}

// ---- RclInterfacesGetParameterTypes (service) ----
class RclInterfacesGetParameterTypes
    extends BaseRosService<RclInterfacesGetParameterTypes_Request, RclInterfacesGetParameterTypes_Response> {
  @override
  String get typeName => 'GetParameterTypes';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesGetParameterTypes_Request createRequest() => RclInterfacesGetParameterTypes_Request();

  @override
  RclInterfacesGetParameterTypes_Response createResponse() => RclInterfacesGetParameterTypes_Response();
}
