// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- rcl_interfaces__msg__IntegerRange ----
base class rcl_interfaces__msg__IntegerRange extends ffi.Struct {
  @ffi.Int64()
  external int from_value;
  @ffi.Int64()
  external int to_value;
  @ffi.Uint64()
  external int step;
}

final class rcl_interfaces__msg__IntegerRange__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__IntegerRange> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesIntegerRange extends BaseRosMessage<rcl_interfaces__msg__IntegerRange> {
  @override
  String get typeName => 'IntegerRange';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesIntegerRange() {
    data = calloc<rcl_interfaces__msg__IntegerRange>();
  }

  int get fromValue =>
      data.ref.from_value;
  set fromValue(int val) =>
      data.ref.from_value = val;
  int get toValue =>
      data.ref.to_value;
  set toValue(int val) =>
      data.ref.to_value = val;
  int get step =>
      data.ref.step;
  set step(int val) =>
      data.ref.step = val;
}
