// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'list_parameters_result.dart';

// ---- rcl_interfaces__srv__ListParameters_Request ----
base class rcl_interfaces__srv__ListParameters_Request extends ffi.Struct {
  external rosidl_runtime_c__String__Sequence prefixes;
  @ffi.Uint64()
  external int depth;
}

final class rcl_interfaces__srv__ListParameters_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__ListParameters_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesListParameters_Request extends BaseRosMessage<rcl_interfaces__srv__ListParameters_Request> {
  @override
  String get typeName => 'ListParameters_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesListParameters_Request() {
    data = calloc<rcl_interfaces__srv__ListParameters_Request>();
  }

  static const int DEPTH_RECURSIVE =
      0;
  List<String> get prefixes {
    final s = data.ref.prefixes;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set prefixes(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.prefixes.data = a;
    data.ref.prefixes.size = value.length;
    data.ref.prefixes.capacity = value.length;
  }
  int get depth =>
      data.ref.depth;
  set depth(int val) =>
      data.ref.depth = val;
}

// ---- rcl_interfaces__srv__ListParameters_Response ----
base class rcl_interfaces__srv__ListParameters_Response extends ffi.Struct {
  external rcl_interfaces__msg__ListParametersResult result;
}

final class rcl_interfaces__srv__ListParameters_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__ListParameters_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesListParameters_Response extends BaseRosMessage<rcl_interfaces__srv__ListParameters_Response> {
  @override
  String get typeName => 'ListParameters_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesListParameters_Response() {
    data = calloc<rcl_interfaces__srv__ListParameters_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'result' not generated;
  // reach the field directly via `data.ref.result`.
}

// ---- RclInterfacesListParameters (service) ----
class RclInterfacesListParameters
    extends BaseRosService<RclInterfacesListParameters_Request, RclInterfacesListParameters_Response> {
  @override
  String get typeName => 'ListParameters';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesListParameters_Request createRequest() => RclInterfacesListParameters_Request();

  @override
  RclInterfacesListParameters_Response createResponse() => RclInterfacesListParameters_Response();
}
