// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;

// ---- rcl_interfaces__msg__Log ----
base class rcl_interfaces__msg__Log extends ffi.Struct {
  external builtin_interfaces__msg__Time stamp;
  @ffi.Uint8()
  external int level;
  external rosidl_runtime_c__String name;
  external rosidl_runtime_c__String msg;
  external rosidl_runtime_c__String file;
  external rosidl_runtime_c__String function;
  @ffi.Uint32()
  external int line;
}

final class rcl_interfaces__msg__Log__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__Log> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesLog extends BaseRosMessage<rcl_interfaces__msg__Log> {
  @override
  String get typeName => 'Log';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesLog() {
    data = calloc<rcl_interfaces__msg__Log>();
    name = '';
    msg = '';
    file = '';
    function = '';
  }

  static const int DEBUG =
      10;
  static const int INFO =
      20;
  static const int WARN =
      30;
  static const int ERROR =
      40;
  static const int FATAL =
      50;
  // TODO(dart-gen): high-level accessor for 'stamp' not generated;
  // reach the field directly via `data.ref.stamp`.
  int get level =>
      data.ref.level;
  set level(int val) =>
      data.ref.level = val;
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  String get msg {
    final s = data.ref.msg;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set msg(String val) {
    final b = val.toNativeUtf8();
    data.ref.msg.data = b.cast<ffi.Char>();
    data.ref.msg.size = b.length;
    data.ref.msg.capacity = b.length + 1;
  }
  String get file {
    final s = data.ref.file;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set file(String val) {
    final b = val.toNativeUtf8();
    data.ref.file.data = b.cast<ffi.Char>();
    data.ref.file.size = b.length;
    data.ref.file.capacity = b.length + 1;
  }
  String get function {
    final s = data.ref.function;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set function(String val) {
    final b = val.toNativeUtf8();
    data.ref.function.data = b.cast<ffi.Char>();
    data.ref.function.size = b.length;
    data.ref.function.capacity = b.length + 1;
  }
  int get line =>
      data.ref.line;
  set line(int val) =>
      data.ref.line = val;
}
