// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- rcl_interfaces__msg__LoggerLevel ----
base class rcl_interfaces__msg__LoggerLevel extends ffi.Struct {
  external rosidl_runtime_c__String name;
  @ffi.Uint32()
  external int level;
}

final class rcl_interfaces__msg__LoggerLevel__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__LoggerLevel> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesLoggerLevel extends BaseRosMessage<rcl_interfaces__msg__LoggerLevel> {
  @override
  String get typeName => 'LoggerLevel';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesLoggerLevel() {
    data = calloc<rcl_interfaces__msg__LoggerLevel>();
    name = '';
  }

  static const int LOG_LEVEL_UNKNOWN =
      0;
  static const int LOG_LEVEL_DEBUG =
      10;
  static const int LOG_LEVEL_INFO =
      20;
  static const int LOG_LEVEL_WARN =
      30;
  static const int LOG_LEVEL_ERROR =
      40;
  static const int LOG_LEVEL_FATAL =
      50;
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  int get level =>
      data.ref.level;
  set level(int val) =>
      data.ref.level = val;
}
