// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'parameter_descriptor.dart';

// ---- rcl_interfaces__msg__ParameterEventDescriptors ----
base class rcl_interfaces__msg__ParameterEventDescriptors extends ffi.Struct {
  external rcl_interfaces__msg__ParameterDescriptor__Sequence new_parameters;
  external rcl_interfaces__msg__ParameterDescriptor__Sequence changed_parameters;
  external rcl_interfaces__msg__ParameterDescriptor__Sequence deleted_parameters;
}

final class rcl_interfaces__msg__ParameterEventDescriptors__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__ParameterEventDescriptors> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameterEventDescriptors extends BaseRosMessage<rcl_interfaces__msg__ParameterEventDescriptors> {
  @override
  String get typeName => 'ParameterEventDescriptors';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameterEventDescriptors() {
    data = calloc<rcl_interfaces__msg__ParameterEventDescriptors>();
  }

  // TODO(dart-gen): high-level accessor for 'new_parameters' not generated;
  // reach the field directly via `data.ref.new_parameters`.
  // TODO(dart-gen): high-level accessor for 'changed_parameters' not generated;
  // reach the field directly via `data.ref.changed_parameters`.
  // TODO(dart-gen): high-level accessor for 'deleted_parameters' not generated;
  // reach the field directly via `data.ref.deleted_parameters`.
}
