// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'parameter.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;

// ---- rcl_interfaces__msg__ParameterEvent ----
base class rcl_interfaces__msg__ParameterEvent extends ffi.Struct {
  external builtin_interfaces__msg__Time stamp;
  external rosidl_runtime_c__String node;
  external rcl_interfaces__msg__Parameter__Sequence new_parameters;
  external rcl_interfaces__msg__Parameter__Sequence changed_parameters;
  external rcl_interfaces__msg__Parameter__Sequence deleted_parameters;
}

final class rcl_interfaces__msg__ParameterEvent__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__ParameterEvent> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameterEvent extends BaseRosMessage<rcl_interfaces__msg__ParameterEvent> {
  @override
  String get typeName => 'ParameterEvent';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameterEvent() {
    data = calloc<rcl_interfaces__msg__ParameterEvent>();
    node = '';
  }

  // TODO(dart-gen): high-level accessor for 'stamp' not generated;
  // reach the field directly via `data.ref.stamp`.
  String get node {
    final s = data.ref.node;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set node(String val) {
    final b = val.toNativeUtf8();
    data.ref.node.data = b.cast<ffi.Char>();
    data.ref.node.size = b.length;
    data.ref.node.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'new_parameters' not generated;
  // reach the field directly via `data.ref.new_parameters`.
  // TODO(dart-gen): high-level accessor for 'changed_parameters' not generated;
  // reach the field directly via `data.ref.changed_parameters`.
  // TODO(dart-gen): high-level accessor for 'deleted_parameters' not generated;
  // reach the field directly via `data.ref.deleted_parameters`.
}
