// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'parameter_value.dart';

// ---- rcl_interfaces__msg__Parameter ----
base class rcl_interfaces__msg__Parameter extends ffi.Struct {
  external rosidl_runtime_c__String name;
  external rcl_interfaces__msg__ParameterValue value;
}

final class rcl_interfaces__msg__Parameter__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__Parameter> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameter extends BaseRosMessage<rcl_interfaces__msg__Parameter> {
  @override
  String get typeName => 'Parameter';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameter() {
    data = calloc<rcl_interfaces__msg__Parameter>();
    name = '';
  }

  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'value' not generated;
  // reach the field directly via `data.ref.value`.
}
