// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- rcl_interfaces__msg__ParameterType ----
base class rcl_interfaces__msg__ParameterType extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class rcl_interfaces__msg__ParameterType__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__ParameterType> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameterType extends BaseRosMessage<rcl_interfaces__msg__ParameterType> {
  @override
  String get typeName => 'ParameterType';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameterType() {
    data = calloc<rcl_interfaces__msg__ParameterType>();
  }

  static const int PARAMETER_NOT_SET =
      0;
  static const int PARAMETER_BOOL =
      1;
  static const int PARAMETER_INTEGER =
      2;
  static const int PARAMETER_DOUBLE =
      3;
  static const int PARAMETER_STRING =
      4;
  static const int PARAMETER_BYTE_ARRAY =
      5;
  static const int PARAMETER_BOOL_ARRAY =
      6;
  static const int PARAMETER_INTEGER_ARRAY =
      7;
  static const int PARAMETER_DOUBLE_ARRAY =
      8;
  static const int PARAMETER_STRING_ARRAY =
      9;
  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}
