// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'floating_point_range.dart';
import 'integer_range.dart';

// ---- rcl_interfaces__msg__ParameterDescriptor ----
base class rcl_interfaces__msg__ParameterDescriptor extends ffi.Struct {
  external rosidl_runtime_c__String name;
  @ffi.Uint8()
  external int type;
  external rosidl_runtime_c__String description;
  external rosidl_runtime_c__String additional_constraints;
  @ffi.Bool()
  external bool read_only;
  @ffi.Bool()
  external bool dynamic_typing;
  external rcl_interfaces__msg__FloatingPointRange__Sequence floating_point_range;
  external rcl_interfaces__msg__IntegerRange__Sequence integer_range;
}

final class rcl_interfaces__msg__ParameterDescriptor__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__ParameterDescriptor> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameterDescriptor extends BaseRosMessage<rcl_interfaces__msg__ParameterDescriptor> {
  @override
  String get typeName => 'ParameterDescriptor';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameterDescriptor() {
    data = calloc<rcl_interfaces__msg__ParameterDescriptor>();
    name = '';
    description = '';
    additionalConstraints = '';
  }

  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  String get description {
    final s = data.ref.description;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set description(String val) {
    final b = val.toNativeUtf8();
    data.ref.description.data = b.cast<ffi.Char>();
    data.ref.description.size = b.length;
    data.ref.description.capacity = b.length + 1;
  }
  String get additionalConstraints {
    final s = data.ref.additional_constraints;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set additionalConstraints(String val) {
    final b = val.toNativeUtf8();
    data.ref.additional_constraints.data = b.cast<ffi.Char>();
    data.ref.additional_constraints.size = b.length;
    data.ref.additional_constraints.capacity = b.length + 1;
  }
  bool get readOnly =>
      data.ref.read_only;
  set readOnly(bool val) =>
      data.ref.read_only = val;
  bool get dynamicTyping =>
      data.ref.dynamic_typing;
  set dynamicTyping(bool val) =>
      data.ref.dynamic_typing = val;
  // TODO(dart-gen): high-level accessor for 'floating_point_range' not generated;
  // reach the field directly via `data.ref.floating_point_range`.
  // TODO(dart-gen): high-level accessor for 'integer_range' not generated;
  // reach the field directly via `data.ref.integer_range`.
}
