// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- rcl_interfaces__msg__ParameterValue ----
base class rcl_interfaces__msg__ParameterValue extends ffi.Struct {
  @ffi.Uint8()
  external int type;
  @ffi.Bool()
  external bool bool_value;
  @ffi.Int64()
  external int integer_value;
  @ffi.Double()
  external double double_value;
  external rosidl_runtime_c__String string_value;
  external rosidl_runtime_c__octet__Sequence byte_array_value;
  external rosidl_runtime_c__boolean__Sequence bool_array_value;
  external rosidl_runtime_c__int64__Sequence integer_array_value;
  external rosidl_runtime_c__double__Sequence double_array_value;
  external rosidl_runtime_c__String__Sequence string_array_value;
}

final class rcl_interfaces__msg__ParameterValue__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__msg__ParameterValue> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesParameterValue extends BaseRosMessage<rcl_interfaces__msg__ParameterValue> {
  @override
  String get typeName => 'ParameterValue';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesParameterValue() {
    data = calloc<rcl_interfaces__msg__ParameterValue>();
    stringValue = '';
  }

  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  bool get boolValue =>
      data.ref.bool_value;
  set boolValue(bool val) =>
      data.ref.bool_value = val;
  int get integerValue =>
      data.ref.integer_value;
  set integerValue(int val) =>
      data.ref.integer_value = val;
  double get doubleValue =>
      data.ref.double_value;
  set doubleValue(double val) =>
      data.ref.double_value = val;
  String get stringValue {
    final s = data.ref.string_value;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set stringValue(String val) {
    final b = val.toNativeUtf8();
    data.ref.string_value.data = b.cast<ffi.Char>();
    data.ref.string_value.size = b.length;
    data.ref.string_value.capacity = b.length + 1;
  }
  List<int> get byteArrayValue {
    final s = data.ref.byte_array_value;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set byteArrayValue(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.byte_array_value.data = a;
    data.ref.byte_array_value.size = value.length;
    data.ref.byte_array_value.capacity = value.length;
  }
  List<bool> get boolArrayValue {
    final s = data.ref.bool_array_value;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set boolArrayValue(List<bool> value) {
    final a = calloc<ffi.Bool>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.bool_array_value.data = a;
    data.ref.bool_array_value.size = value.length;
    data.ref.bool_array_value.capacity = value.length;
  }
  List<int> get integerArrayValue {
    final s = data.ref.integer_array_value;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set integerArrayValue(List<int> value) {
    final a = calloc<ffi.Int64>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.integer_array_value.data = a;
    data.ref.integer_array_value.size = value.length;
    data.ref.integer_array_value.capacity = value.length;
  }
  List<double> get doubleArrayValue {
    final s = data.ref.double_array_value;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set doubleArrayValue(List<double> value) {
    final a = calloc<ffi.Double>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.double_array_value.data = a;
    data.ref.double_array_value.size = value.length;
    data.ref.double_array_value.capacity = value.length;
  }
  List<String> get stringArrayValue {
    final s = data.ref.string_array_value;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set stringArrayValue(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.string_array_value.data = a;
    data.ref.string_array_value.size = value.length;
    data.ref.string_array_value.capacity = value.length;
  }
}
