// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'logger_level.dart';
import 'set_logger_levels_result.dart';

// ---- rcl_interfaces__srv__SetLoggerLevels_Request ----
base class rcl_interfaces__srv__SetLoggerLevels_Request extends ffi.Struct {
  external rcl_interfaces__msg__LoggerLevel__Sequence levels;
}

final class rcl_interfaces__srv__SetLoggerLevels_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetLoggerLevels_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetLoggerLevels_Request extends BaseRosMessage<rcl_interfaces__srv__SetLoggerLevels_Request> {
  @override
  String get typeName => 'SetLoggerLevels_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetLoggerLevels_Request() {
    data = calloc<rcl_interfaces__srv__SetLoggerLevels_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'levels' not generated;
  // reach the field directly via `data.ref.levels`.
}

// ---- rcl_interfaces__srv__SetLoggerLevels_Response ----
base class rcl_interfaces__srv__SetLoggerLevels_Response extends ffi.Struct {
  external rcl_interfaces__msg__SetLoggerLevelsResult__Sequence results;
}

final class rcl_interfaces__srv__SetLoggerLevels_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetLoggerLevels_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetLoggerLevels_Response extends BaseRosMessage<rcl_interfaces__srv__SetLoggerLevels_Response> {
  @override
  String get typeName => 'SetLoggerLevels_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetLoggerLevels_Response() {
    data = calloc<rcl_interfaces__srv__SetLoggerLevels_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'results' not generated;
  // reach the field directly via `data.ref.results`.
}

// ---- RclInterfacesSetLoggerLevels (service) ----
class RclInterfacesSetLoggerLevels
    extends BaseRosService<RclInterfacesSetLoggerLevels_Request, RclInterfacesSetLoggerLevels_Response> {
  @override
  String get typeName => 'SetLoggerLevels';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesSetLoggerLevels_Request createRequest() => RclInterfacesSetLoggerLevels_Request();

  @override
  RclInterfacesSetLoggerLevels_Response createResponse() => RclInterfacesSetLoggerLevels_Response();
}
