// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'parameter.dart';
import 'set_parameters_result.dart';

// ---- rcl_interfaces__srv__SetParameters_Request ----
base class rcl_interfaces__srv__SetParameters_Request extends ffi.Struct {
  external rcl_interfaces__msg__Parameter__Sequence parameters;
}

final class rcl_interfaces__srv__SetParameters_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetParameters_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetParameters_Request extends BaseRosMessage<rcl_interfaces__srv__SetParameters_Request> {
  @override
  String get typeName => 'SetParameters_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetParameters_Request() {
    data = calloc<rcl_interfaces__srv__SetParameters_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'parameters' not generated;
  // reach the field directly via `data.ref.parameters`.
}

// ---- rcl_interfaces__srv__SetParameters_Response ----
base class rcl_interfaces__srv__SetParameters_Response extends ffi.Struct {
  external rcl_interfaces__msg__SetParametersResult__Sequence results;
}

final class rcl_interfaces__srv__SetParameters_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetParameters_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetParameters_Response extends BaseRosMessage<rcl_interfaces__srv__SetParameters_Response> {
  @override
  String get typeName => 'SetParameters_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetParameters_Response() {
    data = calloc<rcl_interfaces__srv__SetParameters_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'results' not generated;
  // reach the field directly via `data.ref.results`.
}

// ---- RclInterfacesSetParameters (service) ----
class RclInterfacesSetParameters
    extends BaseRosService<RclInterfacesSetParameters_Request, RclInterfacesSetParameters_Response> {
  @override
  String get typeName => 'SetParameters';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesSetParameters_Request createRequest() => RclInterfacesSetParameters_Request();

  @override
  RclInterfacesSetParameters_Response createResponse() => RclInterfacesSetParameters_Response();
}
