// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'parameter.dart';
import 'set_parameters_result.dart';

// ---- rcl_interfaces__srv__SetParametersAtomically_Request ----
base class rcl_interfaces__srv__SetParametersAtomically_Request extends ffi.Struct {
  external rcl_interfaces__msg__Parameter__Sequence parameters;
}

final class rcl_interfaces__srv__SetParametersAtomically_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetParametersAtomically_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetParametersAtomically_Request extends BaseRosMessage<rcl_interfaces__srv__SetParametersAtomically_Request> {
  @override
  String get typeName => 'SetParametersAtomically_Request';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetParametersAtomically_Request() {
    data = calloc<rcl_interfaces__srv__SetParametersAtomically_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'parameters' not generated;
  // reach the field directly via `data.ref.parameters`.
}

// ---- rcl_interfaces__srv__SetParametersAtomically_Response ----
base class rcl_interfaces__srv__SetParametersAtomically_Response extends ffi.Struct {
  external rcl_interfaces__msg__SetParametersResult result;
}

final class rcl_interfaces__srv__SetParametersAtomically_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<rcl_interfaces__srv__SetParametersAtomically_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class RclInterfacesSetParametersAtomically_Response extends BaseRosMessage<rcl_interfaces__srv__SetParametersAtomically_Response> {
  @override
  String get typeName => 'SetParametersAtomically_Response';
  @override
  String get packageName => 'rcl_interfaces';

  RclInterfacesSetParametersAtomically_Response() {
    data = calloc<rcl_interfaces__srv__SetParametersAtomically_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'result' not generated;
  // reach the field directly via `data.ref.result`.
}

// ---- RclInterfacesSetParametersAtomically (service) ----
class RclInterfacesSetParametersAtomically
    extends BaseRosService<RclInterfacesSetParametersAtomically_Request, RclInterfacesSetParametersAtomically_Response> {
  @override
  String get typeName => 'SetParametersAtomically';
  @override
  String get packageName => 'rcl_interfaces';

  @override
  RclInterfacesSetParametersAtomically_Request createRequest() => RclInterfacesSetParametersAtomically_Request();

  @override
  RclInterfacesSetParametersAtomically_Response createResponse() => RclInterfacesSetParametersAtomically_Response();
}
