// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'interactive_marker.dart';

// ---- visualization_msgs__srv__GetInteractiveMarkers_Request ----
base class visualization_msgs__srv__GetInteractiveMarkers_Request extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class visualization_msgs__srv__GetInteractiveMarkers_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__srv__GetInteractiveMarkers_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsGetInteractiveMarkers_Request extends BaseRosMessage<visualization_msgs__srv__GetInteractiveMarkers_Request> {
  @override
  String get typeName => 'GetInteractiveMarkers_Request';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsGetInteractiveMarkers_Request() {
    data = calloc<visualization_msgs__srv__GetInteractiveMarkers_Request>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}

// ---- visualization_msgs__srv__GetInteractiveMarkers_Response ----
base class visualization_msgs__srv__GetInteractiveMarkers_Response extends ffi.Struct {
  @ffi.Uint64()
  external int sequence_number;
  external visualization_msgs__msg__InteractiveMarker__Sequence markers;
}

final class visualization_msgs__srv__GetInteractiveMarkers_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__srv__GetInteractiveMarkers_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsGetInteractiveMarkers_Response extends BaseRosMessage<visualization_msgs__srv__GetInteractiveMarkers_Response> {
  @override
  String get typeName => 'GetInteractiveMarkers_Response';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsGetInteractiveMarkers_Response() {
    data = calloc<visualization_msgs__srv__GetInteractiveMarkers_Response>();
  }

  int get sequenceNumber =>
      data.ref.sequence_number;
  set sequenceNumber(int val) =>
      data.ref.sequence_number = val;
  // TODO(dart-gen): high-level accessor for 'markers' not generated;
  // reach the field directly via `data.ref.markers`.
}

// ---- VisualizationMsgsGetInteractiveMarkers (service) ----
class VisualizationMsgsGetInteractiveMarkers
    extends BaseRosService<VisualizationMsgsGetInteractiveMarkers_Request, VisualizationMsgsGetInteractiveMarkers_Response> {
  @override
  String get typeName => 'GetInteractiveMarkers';
  @override
  String get packageName => 'visualization_msgs';

  @override
  VisualizationMsgsGetInteractiveMarkers_Request createRequest() => VisualizationMsgsGetInteractiveMarkers_Request();

  @override
  VisualizationMsgsGetInteractiveMarkers_Response createResponse() => VisualizationMsgsGetInteractiveMarkers_Response();
}
