// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__ImageMarker ----
base class visualization_msgs__msg__ImageMarker extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String ns;
  @ffi.Int32()
  external int id;
  @ffi.Int32()
  external int type;
  @ffi.Int32()
  external int action;
  external geometry_msgs__msg__Point position;
  @ffi.Float()
  external double scale;
  external std_msgs__msg__ColorRGBA outline_color;
  @ffi.Uint8()
  external int filled;
  external std_msgs__msg__ColorRGBA fill_color;
  external builtin_interfaces__msg__Duration lifetime;
  external geometry_msgs__msg__Point__Sequence points;
  external std_msgs__msg__ColorRGBA__Sequence outline_colors;
}

final class visualization_msgs__msg__ImageMarker__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__ImageMarker> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsImageMarker extends BaseRosMessage<visualization_msgs__msg__ImageMarker> {
  @override
  String get typeName => 'ImageMarker';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsImageMarker() {
    data = calloc<visualization_msgs__msg__ImageMarker>();
    ns = '';
  }

  static const int CIRCLE =
      0;
  static const int LINE_STRIP =
      1;
  static const int LINE_LIST =
      2;
  static const int POLYGON =
      3;
  static const int POINTS =
      4;
  static const int ADD =
      0;
  static const int REMOVE =
      1;
  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get ns {
    final s = data.ref.ns;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set ns(String val) {
    final b = val.toNativeUtf8();
    data.ref.ns.data = b.cast<ffi.Char>();
    data.ref.ns.size = b.length;
    data.ref.ns.capacity = b.length + 1;
  }
  int get id =>
      data.ref.id;
  set id(int val) =>
      data.ref.id = val;
  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  int get action =>
      data.ref.action;
  set action(int val) =>
      data.ref.action = val;
  // TODO(dart-gen): high-level accessor for 'position' not generated;
  // reach the field directly via `data.ref.position`.
  double get scale =>
      data.ref.scale;
  set scale(double val) =>
      data.ref.scale = val;
  // TODO(dart-gen): high-level accessor for 'outline_color' not generated;
  // reach the field directly via `data.ref.outline_color`.
  int get filled =>
      data.ref.filled;
  set filled(int val) =>
      data.ref.filled = val;
  // TODO(dart-gen): high-level accessor for 'fill_color' not generated;
  // reach the field directly via `data.ref.fill_color`.
  // TODO(dart-gen): high-level accessor for 'lifetime' not generated;
  // reach the field directly via `data.ref.lifetime`.
  // TODO(dart-gen): high-level accessor for 'points' not generated;
  // reach the field directly via `data.ref.points`.
  // TODO(dart-gen): high-level accessor for 'outline_colors' not generated;
  // reach the field directly via `data.ref.outline_colors`.
}
