// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'interactive_marker.dart';

// ---- visualization_msgs__msg__InteractiveMarkerInit ----
base class visualization_msgs__msg__InteractiveMarkerInit extends ffi.Struct {
  external rosidl_runtime_c__String server_id;
  @ffi.Uint64()
  external int seq_num;
  external visualization_msgs__msg__InteractiveMarker__Sequence markers;
}

final class visualization_msgs__msg__InteractiveMarkerInit__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarkerInit> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarkerInit extends BaseRosMessage<visualization_msgs__msg__InteractiveMarkerInit> {
  @override
  String get typeName => 'InteractiveMarkerInit';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarkerInit() {
    data = calloc<visualization_msgs__msg__InteractiveMarkerInit>();
    serverId = '';
  }

  String get serverId {
    final s = data.ref.server_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set serverId(String val) {
    final b = val.toNativeUtf8();
    data.ref.server_id.data = b.cast<ffi.Char>();
    data.ref.server_id.size = b.length;
    data.ref.server_id.capacity = b.length + 1;
  }
  int get seqNum =>
      data.ref.seq_num;
  set seqNum(int val) =>
      data.ref.seq_num = val;
  // TODO(dart-gen): high-level accessor for 'markers' not generated;
  // reach the field directly via `data.ref.markers`.
}
