// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'interactive_marker.dart';
import 'interactive_marker_pose.dart';

// ---- visualization_msgs__msg__InteractiveMarkerUpdate ----
base class visualization_msgs__msg__InteractiveMarkerUpdate extends ffi.Struct {
  external rosidl_runtime_c__String server_id;
  @ffi.Uint64()
  external int seq_num;
  @ffi.Uint8()
  external int type;
  external visualization_msgs__msg__InteractiveMarker__Sequence markers;
  external visualization_msgs__msg__InteractiveMarkerPose__Sequence poses;
  external rosidl_runtime_c__String__Sequence erases;
}

final class visualization_msgs__msg__InteractiveMarkerUpdate__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarkerUpdate> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarkerUpdate extends BaseRosMessage<visualization_msgs__msg__InteractiveMarkerUpdate> {
  @override
  String get typeName => 'InteractiveMarkerUpdate';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarkerUpdate() {
    data = calloc<visualization_msgs__msg__InteractiveMarkerUpdate>();
    serverId = '';
  }

  static const int KEEP_ALIVE =
      0;
  static const int UPDATE =
      1;
  String get serverId {
    final s = data.ref.server_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set serverId(String val) {
    final b = val.toNativeUtf8();
    data.ref.server_id.data = b.cast<ffi.Char>();
    data.ref.server_id.size = b.length;
    data.ref.server_id.capacity = b.length + 1;
  }
  int get seqNum =>
      data.ref.seq_num;
  set seqNum(int val) =>
      data.ref.seq_num = val;
  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  // TODO(dart-gen): high-level accessor for 'markers' not generated;
  // reach the field directly via `data.ref.markers`.
  // TODO(dart-gen): high-level accessor for 'poses' not generated;
  // reach the field directly via `data.ref.poses`.
  List<String> get erases {
    final s = data.ref.erases;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set erases(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.erases.data = a;
    data.ref.erases.size = value.length;
    data.ref.erases.capacity = value.length;
  }
}
