// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__InteractiveMarkerPose ----
base class visualization_msgs__msg__InteractiveMarkerPose extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Pose pose;
  external rosidl_runtime_c__String name;
}

final class visualization_msgs__msg__InteractiveMarkerPose__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarkerPose> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarkerPose extends BaseRosMessage<visualization_msgs__msg__InteractiveMarkerPose> {
  @override
  String get typeName => 'InteractiveMarkerPose';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarkerPose() {
    data = calloc<visualization_msgs__msg__InteractiveMarkerPose>();
    name = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
}
