// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'interactive_marker_control.dart';
import 'menu_entry.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__InteractiveMarker ----
base class visualization_msgs__msg__InteractiveMarker extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Pose pose;
  external rosidl_runtime_c__String name;
  external rosidl_runtime_c__String description;
  @ffi.Float()
  external double scale;
  external visualization_msgs__msg__MenuEntry__Sequence menu_entries;
  external visualization_msgs__msg__InteractiveMarkerControl__Sequence controls;
}

final class visualization_msgs__msg__InteractiveMarker__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarker> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarker extends BaseRosMessage<visualization_msgs__msg__InteractiveMarker> {
  @override
  String get typeName => 'InteractiveMarker';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarker() {
    data = calloc<visualization_msgs__msg__InteractiveMarker>();
    name = '';
    description = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  String get description {
    final s = data.ref.description;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set description(String val) {
    final b = val.toNativeUtf8();
    data.ref.description.data = b.cast<ffi.Char>();
    data.ref.description.size = b.length;
    data.ref.description.capacity = b.length + 1;
  }
  double get scale =>
      data.ref.scale;
  set scale(double val) =>
      data.ref.scale = val;
  // TODO(dart-gen): high-level accessor for 'menu_entries' not generated;
  // reach the field directly via `data.ref.menu_entries`.
  // TODO(dart-gen): high-level accessor for 'controls' not generated;
  // reach the field directly via `data.ref.controls`.
}
