// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__InteractiveMarkerFeedback ----
base class visualization_msgs__msg__InteractiveMarkerFeedback extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String client_id;
  external rosidl_runtime_c__String marker_name;
  external rosidl_runtime_c__String control_name;
  @ffi.Uint8()
  external int event_type;
  external geometry_msgs__msg__Pose pose;
  @ffi.Uint32()
  external int menu_entry_id;
  external geometry_msgs__msg__Point mouse_point;
  @ffi.Bool()
  external bool mouse_point_valid;
}

final class visualization_msgs__msg__InteractiveMarkerFeedback__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarkerFeedback> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarkerFeedback extends BaseRosMessage<visualization_msgs__msg__InteractiveMarkerFeedback> {
  @override
  String get typeName => 'InteractiveMarkerFeedback';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarkerFeedback() {
    data = calloc<visualization_msgs__msg__InteractiveMarkerFeedback>();
    clientId = '';
    markerName = '';
    controlName = '';
  }

  static const int KEEP_ALIVE =
      0;
  static const int POSE_UPDATE =
      1;
  static const int MENU_SELECT =
      2;
  static const int BUTTON_CLICK =
      3;
  static const int MOUSE_DOWN =
      4;
  static const int MOUSE_UP =
      5;
  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get clientId {
    final s = data.ref.client_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set clientId(String val) {
    final b = val.toNativeUtf8();
    data.ref.client_id.data = b.cast<ffi.Char>();
    data.ref.client_id.size = b.length;
    data.ref.client_id.capacity = b.length + 1;
  }
  String get markerName {
    final s = data.ref.marker_name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set markerName(String val) {
    final b = val.toNativeUtf8();
    data.ref.marker_name.data = b.cast<ffi.Char>();
    data.ref.marker_name.size = b.length;
    data.ref.marker_name.capacity = b.length + 1;
  }
  String get controlName {
    final s = data.ref.control_name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set controlName(String val) {
    final b = val.toNativeUtf8();
    data.ref.control_name.data = b.cast<ffi.Char>();
    data.ref.control_name.size = b.length;
    data.ref.control_name.capacity = b.length + 1;
  }
  int get eventType =>
      data.ref.event_type;
  set eventType(int val) =>
      data.ref.event_type = val;
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  int get menuEntryId =>
      data.ref.menu_entry_id;
  set menuEntryId(int val) =>
      data.ref.menu_entry_id = val;
  // TODO(dart-gen): high-level accessor for 'mouse_point' not generated;
  // reach the field directly via `data.ref.mouse_point`.
  bool get mousePointValid =>
      data.ref.mouse_point_valid;
  set mousePointValid(bool val) =>
      data.ref.mouse_point_valid = val;
}
