// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'marker.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__InteractiveMarkerControl ----
base class visualization_msgs__msg__InteractiveMarkerControl extends ffi.Struct {
  external rosidl_runtime_c__String name;
  external geometry_msgs__msg__Quaternion orientation;
  @ffi.Uint8()
  external int orientation_mode;
  @ffi.Uint8()
  external int interaction_mode;
  @ffi.Bool()
  external bool always_visible;
  external visualization_msgs__msg__Marker__Sequence markers;
  @ffi.Bool()
  external bool independent_marker_orientation;
  external rosidl_runtime_c__String description;
}

final class visualization_msgs__msg__InteractiveMarkerControl__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__InteractiveMarkerControl> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsInteractiveMarkerControl extends BaseRosMessage<visualization_msgs__msg__InteractiveMarkerControl> {
  @override
  String get typeName => 'InteractiveMarkerControl';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsInteractiveMarkerControl() {
    data = calloc<visualization_msgs__msg__InteractiveMarkerControl>();
    name = '';
    description = '';
  }

  static const int INHERIT =
      0;
  static const int FIXED =
      1;
  static const int VIEW_FACING =
      2;
  static const int NONE =
      0;
  static const int MENU =
      1;
  static const int BUTTON =
      2;
  static const int MOVE_AXIS =
      3;
  static const int MOVE_PLANE =
      4;
  static const int ROTATE_AXIS =
      5;
  static const int MOVE_ROTATE =
      6;
  static const int MOVE_3D =
      7;
  static const int ROTATE_3D =
      8;
  static const int MOVE_ROTATE_3D =
      9;
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'orientation' not generated;
  // reach the field directly via `data.ref.orientation`.
  int get orientationMode =>
      data.ref.orientation_mode;
  set orientationMode(int val) =>
      data.ref.orientation_mode = val;
  int get interactionMode =>
      data.ref.interaction_mode;
  set interactionMode(int val) =>
      data.ref.interaction_mode = val;
  bool get alwaysVisible =>
      data.ref.always_visible;
  set alwaysVisible(bool val) =>
      data.ref.always_visible = val;
  // TODO(dart-gen): high-level accessor for 'markers' not generated;
  // reach the field directly via `data.ref.markers`.
  bool get independentMarkerOrientation =>
      data.ref.independent_marker_orientation;
  set independentMarkerOrientation(bool val) =>
      data.ref.independent_marker_orientation = val;
  String get description {
    final s = data.ref.description;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set description(String val) {
    final b = val.toNativeUtf8();
    data.ref.description.data = b.cast<ffi.Char>();
    data.ref.description.size = b.length;
    data.ref.description.capacity = b.length + 1;
  }
}
