// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'mesh_file.dart';
import 'uv_coordinate.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:sensor_msgs/sensor_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- visualization_msgs__msg__Marker ----
base class visualization_msgs__msg__Marker extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String ns;
  @ffi.Int32()
  external int id;
  @ffi.Int32()
  external int type;
  @ffi.Int32()
  external int action;
  external geometry_msgs__msg__Pose pose;
  external geometry_msgs__msg__Vector3 scale;
  external std_msgs__msg__ColorRGBA color;
  external builtin_interfaces__msg__Duration lifetime;
  @ffi.Bool()
  external bool frame_locked;
  external geometry_msgs__msg__Point__Sequence points;
  external std_msgs__msg__ColorRGBA__Sequence colors;
  external rosidl_runtime_c__String texture_resource;
  external sensor_msgs__msg__CompressedImage texture;
  external visualization_msgs__msg__UVCoordinate__Sequence uv_coordinates;
  external rosidl_runtime_c__String text;
  external rosidl_runtime_c__String mesh_resource;
  external visualization_msgs__msg__MeshFile mesh_file;
  @ffi.Bool()
  external bool mesh_use_embedded_materials;
}

final class visualization_msgs__msg__Marker__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__Marker> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsMarker extends BaseRosMessage<visualization_msgs__msg__Marker> {
  @override
  String get typeName => 'Marker';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsMarker() {
    data = calloc<visualization_msgs__msg__Marker>();
    ns = '';
    textureResource = '';
    text = '';
    meshResource = '';
  }

  static const int ARROW =
      0;
  static const int CUBE =
      1;
  static const int SPHERE =
      2;
  static const int CYLINDER =
      3;
  static const int LINE_STRIP =
      4;
  static const int LINE_LIST =
      5;
  static const int CUBE_LIST =
      6;
  static const int SPHERE_LIST =
      7;
  static const int POINTS =
      8;
  static const int TEXT_VIEW_FACING =
      9;
  static const int MESH_RESOURCE =
      10;
  static const int TRIANGLE_LIST =
      11;
  static const int ARROW_STRIP =
      12;
  static const int ADD =
      0;
  static const int MODIFY =
      0;
  static const int DELETE =
      2;
  static const int DELETEALL =
      3;
  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get ns {
    final s = data.ref.ns;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set ns(String val) {
    final b = val.toNativeUtf8();
    data.ref.ns.data = b.cast<ffi.Char>();
    data.ref.ns.size = b.length;
    data.ref.ns.capacity = b.length + 1;
  }
  int get id =>
      data.ref.id;
  set id(int val) =>
      data.ref.id = val;
  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  int get action =>
      data.ref.action;
  set action(int val) =>
      data.ref.action = val;
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  // TODO(dart-gen): high-level accessor for 'scale' not generated;
  // reach the field directly via `data.ref.scale`.
  // TODO(dart-gen): high-level accessor for 'color' not generated;
  // reach the field directly via `data.ref.color`.
  // TODO(dart-gen): high-level accessor for 'lifetime' not generated;
  // reach the field directly via `data.ref.lifetime`.
  bool get frameLocked =>
      data.ref.frame_locked;
  set frameLocked(bool val) =>
      data.ref.frame_locked = val;
  // TODO(dart-gen): high-level accessor for 'points' not generated;
  // reach the field directly via `data.ref.points`.
  // TODO(dart-gen): high-level accessor for 'colors' not generated;
  // reach the field directly via `data.ref.colors`.
  String get textureResource {
    final s = data.ref.texture_resource;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set textureResource(String val) {
    final b = val.toNativeUtf8();
    data.ref.texture_resource.data = b.cast<ffi.Char>();
    data.ref.texture_resource.size = b.length;
    data.ref.texture_resource.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'texture' not generated;
  // reach the field directly via `data.ref.texture`.
  // TODO(dart-gen): high-level accessor for 'uv_coordinates' not generated;
  // reach the field directly via `data.ref.uv_coordinates`.
  String get text {
    final s = data.ref.text;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set text(String val) {
    final b = val.toNativeUtf8();
    data.ref.text.data = b.cast<ffi.Char>();
    data.ref.text.size = b.length;
    data.ref.text.capacity = b.length + 1;
  }
  String get meshResource {
    final s = data.ref.mesh_resource;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set meshResource(String val) {
    final b = val.toNativeUtf8();
    data.ref.mesh_resource.data = b.cast<ffi.Char>();
    data.ref.mesh_resource.size = b.length;
    data.ref.mesh_resource.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'mesh_file' not generated;
  // reach the field directly via `data.ref.mesh_file`.
  bool get meshUseEmbeddedMaterials =>
      data.ref.mesh_use_embedded_materials;
  set meshUseEmbeddedMaterials(bool val) =>
      data.ref.mesh_use_embedded_materials = val;
}
