// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'marker.dart';

// ---- visualization_msgs__msg__MarkerArray ----
base class visualization_msgs__msg__MarkerArray extends ffi.Struct {
  external visualization_msgs__msg__Marker__Sequence markers;
}

final class visualization_msgs__msg__MarkerArray__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__MarkerArray> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsMarkerArray extends BaseRosMessage<visualization_msgs__msg__MarkerArray> {
  @override
  String get typeName => 'MarkerArray';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsMarkerArray() {
    data = calloc<visualization_msgs__msg__MarkerArray>();
  }

  // TODO(dart-gen): high-level accessor for 'markers' not generated;
  // reach the field directly via `data.ref.markers`.
}
