// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- visualization_msgs__msg__MenuEntry ----
base class visualization_msgs__msg__MenuEntry extends ffi.Struct {
  @ffi.Uint32()
  external int id;
  @ffi.Uint32()
  external int parent_id;
  external rosidl_runtime_c__String title;
  external rosidl_runtime_c__String command;
  @ffi.Uint8()
  external int command_type;
}

final class visualization_msgs__msg__MenuEntry__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__MenuEntry> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsMenuEntry extends BaseRosMessage<visualization_msgs__msg__MenuEntry> {
  @override
  String get typeName => 'MenuEntry';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsMenuEntry() {
    data = calloc<visualization_msgs__msg__MenuEntry>();
    title = '';
    command = '';
  }

  static const int FEEDBACK =
      0;
  static const int ROSRUN =
      1;
  static const int ROSLAUNCH =
      2;
  int get id =>
      data.ref.id;
  set id(int val) =>
      data.ref.id = val;
  int get parentId =>
      data.ref.parent_id;
  set parentId(int val) =>
      data.ref.parent_id = val;
  String get title {
    final s = data.ref.title;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set title(String val) {
    final b = val.toNativeUtf8();
    data.ref.title.data = b.cast<ffi.Char>();
    data.ref.title.size = b.length;
    data.ref.title.capacity = b.length + 1;
  }
  String get command {
    final s = data.ref.command;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set command(String val) {
    final b = val.toNativeUtf8();
    data.ref.command.data = b.cast<ffi.Char>();
    data.ref.command.size = b.length;
    data.ref.command.capacity = b.length + 1;
  }
  int get commandType =>
      data.ref.command_type;
  set commandType(int val) =>
      data.ref.command_type = val;
}
