// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- visualization_msgs__msg__MeshFile ----
base class visualization_msgs__msg__MeshFile extends ffi.Struct {
  external rosidl_runtime_c__String filename;
  external rosidl_runtime_c__uint8__Sequence data;
}

final class visualization_msgs__msg__MeshFile__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__MeshFile> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsMeshFile extends BaseRosMessage<visualization_msgs__msg__MeshFile> {
  @override
  String get typeName => 'MeshFile';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsMeshFile() {
    data = calloc<visualization_msgs__msg__MeshFile>();
    filename = '';
  }

  String get filename {
    final s = data.ref.filename;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set filename(String val) {
    final b = val.toNativeUtf8();
    data.ref.filename.data = b.cast<ffi.Char>();
    data.ref.filename.size = b.length;
    data.ref.filename.capacity = b.length + 1;
  }
  List<int> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
}
