// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- visualization_msgs__msg__UVCoordinate ----
base class visualization_msgs__msg__UVCoordinate extends ffi.Struct {
  @ffi.Float()
  external double u;
  @ffi.Float()
  external double v;
}

final class visualization_msgs__msg__UVCoordinate__Sequence extends ffi.Struct {
  external ffi.Pointer<visualization_msgs__msg__UVCoordinate> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class VisualizationMsgsUVCoordinate extends BaseRosMessage<visualization_msgs__msg__UVCoordinate> {
  @override
  String get typeName => 'UVCoordinate';
  @override
  String get packageName => 'visualization_msgs';

  VisualizationMsgsUVCoordinate() {
    data = calloc<visualization_msgs__msg__UVCoordinate>();
  }

  double get u =>
      data.ref.u;
  set u(double val) =>
      data.ref.u = val;
  double get v =>
      data.ref.v;
  set v(double val) =>
      data.ref.v = val;
}
