// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__BatteryState ----
base class sensor_msgs__msg__BatteryState extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Float()
  external double voltage;
  @ffi.Float()
  external double temperature;
  @ffi.Float()
  external double current;
  @ffi.Float()
  external double charge;
  @ffi.Float()
  external double capacity;
  @ffi.Float()
  external double design_capacity;
  @ffi.Float()
  external double percentage;
  @ffi.Uint8()
  external int power_supply_status;
  @ffi.Uint8()
  external int power_supply_health;
  @ffi.Uint8()
  external int power_supply_technology;
  @ffi.Bool()
  external bool present;
  external rosidl_runtime_c__float__Sequence cell_voltage;
  external rosidl_runtime_c__float__Sequence cell_temperature;
  external rosidl_runtime_c__String location;
  external rosidl_runtime_c__String serial_number;
}

final class sensor_msgs__msg__BatteryState__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__BatteryState> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsBatteryState extends BaseRosMessage<sensor_msgs__msg__BatteryState> {
  @override
  String get typeName => 'BatteryState';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsBatteryState() {
    data = calloc<sensor_msgs__msg__BatteryState>();
    location = '';
    serialNumber = '';
  }

  static const int POWER_SUPPLY_STATUS_UNKNOWN =
      0;
  static const int POWER_SUPPLY_STATUS_CHARGING =
      1;
  static const int POWER_SUPPLY_STATUS_DISCHARGING =
      2;
  static const int POWER_SUPPLY_STATUS_NOT_CHARGING =
      3;
  static const int POWER_SUPPLY_STATUS_FULL =
      4;
  static const int POWER_SUPPLY_HEALTH_UNKNOWN =
      0;
  static const int POWER_SUPPLY_HEALTH_GOOD =
      1;
  static const int POWER_SUPPLY_HEALTH_OVERHEAT =
      2;
  static const int POWER_SUPPLY_HEALTH_DEAD =
      3;
  static const int POWER_SUPPLY_HEALTH_OVERVOLTAGE =
      4;
  static const int POWER_SUPPLY_HEALTH_UNSPEC_FAILURE =
      5;
  static const int POWER_SUPPLY_HEALTH_COLD =
      6;
  static const int POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE =
      7;
  static const int POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE =
      8;
  static const int POWER_SUPPLY_TECHNOLOGY_UNKNOWN =
      0;
  static const int POWER_SUPPLY_TECHNOLOGY_NIMH =
      1;
  static const int POWER_SUPPLY_TECHNOLOGY_LION =
      2;
  static const int POWER_SUPPLY_TECHNOLOGY_LIPO =
      3;
  static const int POWER_SUPPLY_TECHNOLOGY_LIFE =
      4;
  static const int POWER_SUPPLY_TECHNOLOGY_NICD =
      5;
  static const int POWER_SUPPLY_TECHNOLOGY_LIMN =
      6;
  static const int POWER_SUPPLY_TECHNOLOGY_TERNARY =
      7;
  static const int POWER_SUPPLY_TECHNOLOGY_VRLA =
      8;
  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get voltage =>
      data.ref.voltage;
  set voltage(double val) =>
      data.ref.voltage = val;
  double get temperature =>
      data.ref.temperature;
  set temperature(double val) =>
      data.ref.temperature = val;
  double get current =>
      data.ref.current;
  set current(double val) =>
      data.ref.current = val;
  double get charge =>
      data.ref.charge;
  set charge(double val) =>
      data.ref.charge = val;
  double get capacity =>
      data.ref.capacity;
  set capacity(double val) =>
      data.ref.capacity = val;
  double get designCapacity =>
      data.ref.design_capacity;
  set designCapacity(double val) =>
      data.ref.design_capacity = val;
  double get percentage =>
      data.ref.percentage;
  set percentage(double val) =>
      data.ref.percentage = val;
  int get powerSupplyStatus =>
      data.ref.power_supply_status;
  set powerSupplyStatus(int val) =>
      data.ref.power_supply_status = val;
  int get powerSupplyHealth =>
      data.ref.power_supply_health;
  set powerSupplyHealth(int val) =>
      data.ref.power_supply_health = val;
  int get powerSupplyTechnology =>
      data.ref.power_supply_technology;
  set powerSupplyTechnology(int val) =>
      data.ref.power_supply_technology = val;
  bool get present =>
      data.ref.present;
  set present(bool val) =>
      data.ref.present = val;
  List<double> get cellVoltage {
    final s = data.ref.cell_voltage;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set cellVoltage(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.cell_voltage.data = a;
    data.ref.cell_voltage.size = value.length;
    data.ref.cell_voltage.capacity = value.length;
  }
  List<double> get cellTemperature {
    final s = data.ref.cell_temperature;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set cellTemperature(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.cell_temperature.data = a;
    data.ref.cell_temperature.size = value.length;
    data.ref.cell_temperature.capacity = value.length;
  }
  String get location {
    final s = data.ref.location;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set location(String val) {
    final b = val.toNativeUtf8();
    data.ref.location.data = b.cast<ffi.Char>();
    data.ref.location.size = b.length;
    data.ref.location.capacity = b.length + 1;
  }
  String get serialNumber {
    final s = data.ref.serial_number;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set serialNumber(String val) {
    final b = val.toNativeUtf8();
    data.ref.serial_number.data = b.cast<ffi.Char>();
    data.ref.serial_number.size = b.length;
    data.ref.serial_number.capacity = b.length + 1;
  }
}
