// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'region_of_interest.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__CameraInfo ----
base class sensor_msgs__msg__CameraInfo extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Uint32()
  external int height;
  @ffi.Uint32()
  external int width;
  external rosidl_runtime_c__String distortion_model;
  external rosidl_runtime_c__double__Sequence d;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> k;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> r;
  @ffi.Array(12)
  external ffi.Array<ffi.Double> p;
  @ffi.Uint32()
  external int binning_x;
  @ffi.Uint32()
  external int binning_y;
  external sensor_msgs__msg__RegionOfInterest roi;
}

final class sensor_msgs__msg__CameraInfo__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__CameraInfo> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsCameraInfo extends BaseRosMessage<sensor_msgs__msg__CameraInfo> {
  @override
  String get typeName => 'CameraInfo';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsCameraInfo() {
    data = calloc<sensor_msgs__msg__CameraInfo>();
    distortionModel = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  int get height =>
      data.ref.height;
  set height(int val) =>
      data.ref.height = val;
  int get width =>
      data.ref.width;
  set width(int val) =>
      data.ref.width = val;
  String get distortionModel {
    final s = data.ref.distortion_model;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set distortionModel(String val) {
    final b = val.toNativeUtf8();
    data.ref.distortion_model.data = b.cast<ffi.Char>();
    data.ref.distortion_model.size = b.length;
    data.ref.distortion_model.capacity = b.length + 1;
  }
  List<double> get d {
    final s = data.ref.d;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set d(List<double> value) {
    final a = calloc<ffi.Double>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.d.data = a;
    data.ref.d.size = value.length;
    data.ref.d.capacity = value.length;
  }
  List<double> get k =>
      List.generate(9, (i) => data.ref.k[i]);
  set k(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.k[i] = value[i];
    }
  }
  List<double> get r =>
      List.generate(9, (i) => data.ref.r[i]);
  set r(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.r[i] = value[i];
    }
  }
  List<double> get p =>
      List.generate(12, (i) => data.ref.p[i]);
  set p(List<double> value) {
    for (var i = 0; i < 12 && i < value.length; i++) {
      data.ref.p[i] = value[i];
    }
  }
  int get binningX =>
      data.ref.binning_x;
  set binningX(int val) =>
      data.ref.binning_x = val;
  int get binningY =>
      data.ref.binning_y;
  set binningY(int val) =>
      data.ref.binning_y = val;
  // TODO(dart-gen): high-level accessor for 'roi' not generated;
  // reach the field directly via `data.ref.roi`.
}
