// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- sensor_msgs__msg__ChannelFloat32 ----
base class sensor_msgs__msg__ChannelFloat32 extends ffi.Struct {
  external rosidl_runtime_c__String name;
  external rosidl_runtime_c__float__Sequence values;
}

final class sensor_msgs__msg__ChannelFloat32__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__ChannelFloat32> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsChannelFloat32 extends BaseRosMessage<sensor_msgs__msg__ChannelFloat32> {
  @override
  String get typeName => 'ChannelFloat32';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsChannelFloat32() {
    data = calloc<sensor_msgs__msg__ChannelFloat32>();
    name = '';
  }

  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  List<double> get values {
    final s = data.ref.values;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set values(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.values.data = a;
    data.ref.values.size = value.length;
    data.ref.values.capacity = value.length;
  }
}
