// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__CompressedImage ----
base class sensor_msgs__msg__CompressedImage extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String format;
  external rosidl_runtime_c__uint8__Sequence data;
}

final class sensor_msgs__msg__CompressedImage__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__CompressedImage> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsCompressedImage extends BaseRosMessage<sensor_msgs__msg__CompressedImage> {
  @override
  String get typeName => 'CompressedImage';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsCompressedImage() {
    data = calloc<sensor_msgs__msg__CompressedImage>();
    format = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get format {
    final s = data.ref.format;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set format(String val) {
    final b = val.toNativeUtf8();
    data.ref.format.data = b.cast<ffi.Char>();
    data.ref.format.size = b.length;
    data.ref.format.capacity = b.length + 1;
  }
  List<int> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
}
