// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__FluidPressure ----
base class sensor_msgs__msg__FluidPressure extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Double()
  external double fluid_pressure;
  @ffi.Double()
  external double variance;
}

final class sensor_msgs__msg__FluidPressure__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__FluidPressure> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsFluidPressure extends BaseRosMessage<sensor_msgs__msg__FluidPressure> {
  @override
  String get typeName => 'FluidPressure';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsFluidPressure() {
    data = calloc<sensor_msgs__msg__FluidPressure>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get fluidPressure_ =>
      data.ref.fluid_pressure;
  set fluidPressure_(double val) =>
      data.ref.fluid_pressure = val;
  double get variance =>
      data.ref.variance;
  set variance(double val) =>
      data.ref.variance = val;
}
