// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__Illuminance ----
base class sensor_msgs__msg__Illuminance extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Double()
  external double illuminance;
  @ffi.Double()
  external double variance;
}

final class sensor_msgs__msg__Illuminance__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__Illuminance> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsIlluminance extends BaseRosMessage<sensor_msgs__msg__Illuminance> {
  @override
  String get typeName => 'Illuminance';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsIlluminance() {
    data = calloc<sensor_msgs__msg__Illuminance>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get illuminance_ =>
      data.ref.illuminance;
  set illuminance_(double val) =>
      data.ref.illuminance = val;
  double get variance =>
      data.ref.variance;
  set variance(double val) =>
      data.ref.variance = val;
}
