// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__Image ----
base class sensor_msgs__msg__Image extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Uint32()
  external int height;
  @ffi.Uint32()
  external int width;
  external rosidl_runtime_c__String encoding;
  @ffi.Uint8()
  external int is_bigendian;
  @ffi.Uint32()
  external int step;
  external rosidl_runtime_c__uint8__Sequence data;
}

final class sensor_msgs__msg__Image__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__Image> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsImage extends BaseRosMessage<sensor_msgs__msg__Image> {
  @override
  String get typeName => 'Image';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsImage() {
    data = calloc<sensor_msgs__msg__Image>();
    encoding = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  int get height =>
      data.ref.height;
  set height(int val) =>
      data.ref.height = val;
  int get width =>
      data.ref.width;
  set width(int val) =>
      data.ref.width = val;
  String get encoding {
    final s = data.ref.encoding;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set encoding(String val) {
    final b = val.toNativeUtf8();
    data.ref.encoding.data = b.cast<ffi.Char>();
    data.ref.encoding.size = b.length;
    data.ref.encoding.capacity = b.length + 1;
  }
  int get isBigendian =>
      data.ref.is_bigendian;
  set isBigendian(int val) =>
      data.ref.is_bigendian = val;
  int get step =>
      data.ref.step;
  set step(int val) =>
      data.ref.step = val;
  List<int> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
}
