// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:geometry_msgs/geometry_msgs.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__Imu ----
base class sensor_msgs__msg__Imu extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Quaternion orientation;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> orientation_covariance;
  external geometry_msgs__msg__Vector3 angular_velocity;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> angular_velocity_covariance;
  external geometry_msgs__msg__Vector3 linear_acceleration;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> linear_acceleration_covariance;
}

final class sensor_msgs__msg__Imu__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__Imu> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsImu extends BaseRosMessage<sensor_msgs__msg__Imu> {
  @override
  String get typeName => 'Imu';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsImu() {
    data = calloc<sensor_msgs__msg__Imu>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'orientation' not generated;
  // reach the field directly via `data.ref.orientation`.
  List<double> get orientationCovariance =>
      List.generate(9, (i) => data.ref.orientation_covariance[i]);
  set orientationCovariance(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.orientation_covariance[i] = value[i];
    }
  }
  // TODO(dart-gen): high-level accessor for 'angular_velocity' not generated;
  // reach the field directly via `data.ref.angular_velocity`.
  List<double> get angularVelocityCovariance =>
      List.generate(9, (i) => data.ref.angular_velocity_covariance[i]);
  set angularVelocityCovariance(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.angular_velocity_covariance[i] = value[i];
    }
  }
  // TODO(dart-gen): high-level accessor for 'linear_acceleration' not generated;
  // reach the field directly via `data.ref.linear_acceleration`.
  List<double> get linearAccelerationCovariance =>
      List.generate(9, (i) => data.ref.linear_acceleration_covariance[i]);
  set linearAccelerationCovariance(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.linear_acceleration_covariance[i] = value[i];
    }
  }
}
