// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__Joy ----
base class sensor_msgs__msg__Joy extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__float__Sequence axes;
  external rosidl_runtime_c__int32__Sequence buttons;
}

final class sensor_msgs__msg__Joy__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__Joy> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsJoy extends BaseRosMessage<sensor_msgs__msg__Joy> {
  @override
  String get typeName => 'Joy';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsJoy() {
    data = calloc<sensor_msgs__msg__Joy>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  List<double> get axes {
    final s = data.ref.axes;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set axes(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.axes.data = a;
    data.ref.axes.size = value.length;
    data.ref.axes.capacity = value.length;
  }
  List<int> get buttons {
    final s = data.ref.buttons;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set buttons(List<int> value) {
    final a = calloc<ffi.Int32>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.buttons.data = a;
    data.ref.buttons.size = value.length;
    data.ref.buttons.capacity = value.length;
  }
}
