// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'joy_feedback.dart';

// ---- sensor_msgs__msg__JoyFeedbackArray ----
base class sensor_msgs__msg__JoyFeedbackArray extends ffi.Struct {
  external sensor_msgs__msg__JoyFeedback__Sequence array;
}

final class sensor_msgs__msg__JoyFeedbackArray__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__JoyFeedbackArray> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsJoyFeedbackArray extends BaseRosMessage<sensor_msgs__msg__JoyFeedbackArray> {
  @override
  String get typeName => 'JoyFeedbackArray';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsJoyFeedbackArray() {
    data = calloc<sensor_msgs__msg__JoyFeedbackArray>();
  }

  // TODO(dart-gen): high-level accessor for 'array' not generated;
  // reach the field directly via `data.ref.array`.
}
