// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- sensor_msgs__msg__JoyFeedback ----
base class sensor_msgs__msg__JoyFeedback extends ffi.Struct {
  @ffi.Uint8()
  external int type;
  @ffi.Uint8()
  external int id;
  @ffi.Float()
  external double intensity;
}

final class sensor_msgs__msg__JoyFeedback__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__JoyFeedback> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsJoyFeedback extends BaseRosMessage<sensor_msgs__msg__JoyFeedback> {
  @override
  String get typeName => 'JoyFeedback';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsJoyFeedback() {
    data = calloc<sensor_msgs__msg__JoyFeedback>();
  }

  static const int TYPE_LED =
      0;
  static const int TYPE_RUMBLE =
      1;
  static const int TYPE_BUZZER =
      2;
  int get type =>
      data.ref.type;
  set type(int val) =>
      data.ref.type = val;
  int get id =>
      data.ref.id;
  set id(int val) =>
      data.ref.id = val;
  double get intensity =>
      data.ref.intensity;
  set intensity(double val) =>
      data.ref.intensity = val;
}
