// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- sensor_msgs__msg__LaserEcho ----
base class sensor_msgs__msg__LaserEcho extends ffi.Struct {
  external rosidl_runtime_c__float__Sequence echoes;
}

final class sensor_msgs__msg__LaserEcho__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__LaserEcho> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsLaserEcho extends BaseRosMessage<sensor_msgs__msg__LaserEcho> {
  @override
  String get typeName => 'LaserEcho';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsLaserEcho() {
    data = calloc<sensor_msgs__msg__LaserEcho>();
  }

  List<double> get echoes {
    final s = data.ref.echoes;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set echoes(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.echoes.data = a;
    data.ref.echoes.size = value.length;
    data.ref.echoes.capacity = value.length;
  }
}
