// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:geometry_msgs/geometry_msgs.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__MagneticField ----
base class sensor_msgs__msg__MagneticField extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Vector3 magnetic_field;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> magnetic_field_covariance;
}

final class sensor_msgs__msg__MagneticField__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__MagneticField> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsMagneticField extends BaseRosMessage<sensor_msgs__msg__MagneticField> {
  @override
  String get typeName => 'MagneticField';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsMagneticField() {
    data = calloc<sensor_msgs__msg__MagneticField>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'magnetic_field' not generated;
  // reach the field directly via `data.ref.magnetic_field`.
  List<double> get magneticFieldCovariance =>
      List.generate(9, (i) => data.ref.magnetic_field_covariance[i]);
  set magneticFieldCovariance(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.magnetic_field_covariance[i] = value[i];
    }
  }
}
