// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'laser_echo.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__MultiEchoLaserScan ----
base class sensor_msgs__msg__MultiEchoLaserScan extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Float()
  external double angle_min;
  @ffi.Float()
  external double angle_max;
  @ffi.Float()
  external double angle_increment;
  @ffi.Float()
  external double time_increment;
  @ffi.Float()
  external double scan_time;
  @ffi.Float()
  external double range_min;
  @ffi.Float()
  external double range_max;
  external sensor_msgs__msg__LaserEcho__Sequence ranges;
  external sensor_msgs__msg__LaserEcho__Sequence intensities;
}

final class sensor_msgs__msg__MultiEchoLaserScan__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__MultiEchoLaserScan> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsMultiEchoLaserScan extends BaseRosMessage<sensor_msgs__msg__MultiEchoLaserScan> {
  @override
  String get typeName => 'MultiEchoLaserScan';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsMultiEchoLaserScan() {
    data = calloc<sensor_msgs__msg__MultiEchoLaserScan>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get angleMin =>
      data.ref.angle_min;
  set angleMin(double val) =>
      data.ref.angle_min = val;
  double get angleMax =>
      data.ref.angle_max;
  set angleMax(double val) =>
      data.ref.angle_max = val;
  double get angleIncrement =>
      data.ref.angle_increment;
  set angleIncrement(double val) =>
      data.ref.angle_increment = val;
  double get timeIncrement =>
      data.ref.time_increment;
  set timeIncrement(double val) =>
      data.ref.time_increment = val;
  double get scanTime =>
      data.ref.scan_time;
  set scanTime(double val) =>
      data.ref.scan_time = val;
  double get rangeMin =>
      data.ref.range_min;
  set rangeMin(double val) =>
      data.ref.range_min = val;
  double get rangeMax =>
      data.ref.range_max;
  set rangeMax(double val) =>
      data.ref.range_max = val;
  // TODO(dart-gen): high-level accessor for 'ranges' not generated;
  // reach the field directly via `data.ref.ranges`.
  // TODO(dart-gen): high-level accessor for 'intensities' not generated;
  // reach the field directly via `data.ref.intensities`.
}
