// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__MultiDOFJointState ----
base class sensor_msgs__msg__MultiDOFJointState extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String__Sequence joint_names;
  external geometry_msgs__msg__Transform__Sequence transforms;
  external geometry_msgs__msg__Twist__Sequence twist;
  external geometry_msgs__msg__Wrench__Sequence wrench;
}

final class sensor_msgs__msg__MultiDOFJointState__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__MultiDOFJointState> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsMultiDOFJointState extends BaseRosMessage<sensor_msgs__msg__MultiDOFJointState> {
  @override
  String get typeName => 'MultiDOFJointState';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsMultiDOFJointState() {
    data = calloc<sensor_msgs__msg__MultiDOFJointState>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  List<String> get jointNames {
    final s = data.ref.joint_names;
    return List.generate(s.size, (i) {
      final e = s.data[i];
      if (e.data == ffi.nullptr || e.size == 0) return '';
      return e.data.cast<Utf8>().toDartString(length: e.size);
    });
  }
  set jointNames(List<String> value) {
    final a = calloc<rosidl_runtime_c__String>(value.length);
    for (var i = 0; i < value.length; i++) {
      final b = value[i].toNativeUtf8();
      a[i].data = b.cast<ffi.Char>();
      a[i].size = b.length;
      a[i].capacity = b.length + 1;
    }
    data.ref.joint_names.data = a;
    data.ref.joint_names.size = value.length;
    data.ref.joint_names.capacity = value.length;
  }
  // TODO(dart-gen): high-level accessor for 'transforms' not generated;
  // reach the field directly via `data.ref.transforms`.
  // TODO(dart-gen): high-level accessor for 'twist' not generated;
  // reach the field directly via `data.ref.twist`.
  // TODO(dart-gen): high-level accessor for 'wrench' not generated;
  // reach the field directly via `data.ref.wrench`.
}
