// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- sensor_msgs__msg__NavSatStatus ----
base class sensor_msgs__msg__NavSatStatus extends ffi.Struct {
  @ffi.Int8()
  external int status;
  @ffi.Uint16()
  external int service;
}

final class sensor_msgs__msg__NavSatStatus__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__NavSatStatus> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsNavSatStatus extends BaseRosMessage<sensor_msgs__msg__NavSatStatus> {
  @override
  String get typeName => 'NavSatStatus';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsNavSatStatus() {
    data = calloc<sensor_msgs__msg__NavSatStatus>();
  }

  static const int STATUS_UNKNOWN =
      -2;
  static const int STATUS_NO_FIX =
      -1;
  static const int STATUS_FIX =
      0;
  static const int STATUS_SBAS_FIX =
      1;
  static const int STATUS_GBAS_FIX =
      2;
  static const int SERVICE_UNKNOWN =
      0;
  static const int SERVICE_GPS =
      1;
  static const int SERVICE_GLONASS =
      2;
  static const int SERVICE_COMPASS =
      4;
  static const int SERVICE_GALILEO =
      8;
  int get status =>
      data.ref.status;
  set status(int val) =>
      data.ref.status = val;
  int get service =>
      data.ref.service;
  set service(int val) =>
      data.ref.service = val;
}
