// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'nav_sat_status.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__NavSatFix ----
base class sensor_msgs__msg__NavSatFix extends ffi.Struct {
  external std_msgs__msg__Header header;
  external sensor_msgs__msg__NavSatStatus status;
  @ffi.Double()
  external double latitude;
  @ffi.Double()
  external double longitude;
  @ffi.Double()
  external double altitude;
  @ffi.Array(9)
  external ffi.Array<ffi.Double> position_covariance;
  @ffi.Uint8()
  external int position_covariance_type;
}

final class sensor_msgs__msg__NavSatFix__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__NavSatFix> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsNavSatFix extends BaseRosMessage<sensor_msgs__msg__NavSatFix> {
  @override
  String get typeName => 'NavSatFix';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsNavSatFix() {
    data = calloc<sensor_msgs__msg__NavSatFix>();
  }

  static const int COVARIANCE_TYPE_UNKNOWN =
      0;
  static const int COVARIANCE_TYPE_APPROXIMATED =
      1;
  static const int COVARIANCE_TYPE_DIAGONAL_KNOWN =
      2;
  static const int COVARIANCE_TYPE_KNOWN =
      3;
  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'status' not generated;
  // reach the field directly via `data.ref.status`.
  double get latitude =>
      data.ref.latitude;
  set latitude(double val) =>
      data.ref.latitude = val;
  double get longitude =>
      data.ref.longitude;
  set longitude(double val) =>
      data.ref.longitude = val;
  double get altitude =>
      data.ref.altitude;
  set altitude(double val) =>
      data.ref.altitude = val;
  List<double> get positionCovariance =>
      List.generate(9, (i) => data.ref.position_covariance[i]);
  set positionCovariance(List<double> value) {
    for (var i = 0; i < 9 && i < value.length; i++) {
      data.ref.position_covariance[i] = value[i];
    }
  }
  int get positionCovarianceType =>
      data.ref.position_covariance_type;
  set positionCovarianceType(int val) =>
      data.ref.position_covariance_type = val;
}
