// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'point_field.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__PointCloud2 ----
base class sensor_msgs__msg__PointCloud2 extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Uint32()
  external int height;
  @ffi.Uint32()
  external int width;
  external sensor_msgs__msg__PointField__Sequence fields;
  @ffi.Bool()
  external bool is_bigendian;
  @ffi.Uint32()
  external int point_step;
  @ffi.Uint32()
  external int row_step;
  external rosidl_runtime_c__uint8__Sequence data;
  @ffi.Bool()
  external bool is_dense;
}

final class sensor_msgs__msg__PointCloud2__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__PointCloud2> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsPointCloud2 extends BaseRosMessage<sensor_msgs__msg__PointCloud2> {
  @override
  String get typeName => 'PointCloud2';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsPointCloud2() {
    data = calloc<sensor_msgs__msg__PointCloud2>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  int get height =>
      data.ref.height;
  set height(int val) =>
      data.ref.height = val;
  int get width =>
      data.ref.width;
  set width(int val) =>
      data.ref.width = val;
  // TODO(dart-gen): high-level accessor for 'fields' not generated;
  // reach the field directly via `data.ref.fields`.
  bool get isBigendian =>
      data.ref.is_bigendian;
  set isBigendian(bool val) =>
      data.ref.is_bigendian = val;
  int get pointStep =>
      data.ref.point_step;
  set pointStep(int val) =>
      data.ref.point_step = val;
  int get rowStep =>
      data.ref.row_step;
  set rowStep(int val) =>
      data.ref.row_step = val;
  List<int> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<int> value) {
    final a = calloc<ffi.Uint8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
  bool get isDense =>
      data.ref.is_dense;
  set isDense(bool val) =>
      data.ref.is_dense = val;
}
