// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- sensor_msgs__msg__PointField ----
base class sensor_msgs__msg__PointField extends ffi.Struct {
  external rosidl_runtime_c__String name;
  @ffi.Uint32()
  external int offset;
  @ffi.Uint8()
  external int datatype;
  @ffi.Uint32()
  external int count;
}

final class sensor_msgs__msg__PointField__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__PointField> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsPointField extends BaseRosMessage<sensor_msgs__msg__PointField> {
  @override
  String get typeName => 'PointField';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsPointField() {
    data = calloc<sensor_msgs__msg__PointField>();
    name = '';
  }

  static const int INT8 =
      1;
  static const int UINT8 =
      2;
  static const int INT16 =
      3;
  static const int UINT16 =
      4;
  static const int INT32 =
      5;
  static const int UINT32 =
      6;
  static const int FLOAT32 =
      7;
  static const int FLOAT64 =
      8;
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  int get offset =>
      data.ref.offset;
  set offset(int val) =>
      data.ref.offset = val;
  int get datatype =>
      data.ref.datatype;
  set datatype(int val) =>
      data.ref.datatype = val;
  int get count =>
      data.ref.count;
  set count(int val) =>
      data.ref.count = val;
}
