// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'channel_float32.dart';
import 'package:geometry_msgs/geometry_msgs.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__PointCloud ----
base class sensor_msgs__msg__PointCloud extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Point32__Sequence points;
  external sensor_msgs__msg__ChannelFloat32__Sequence channels;
}

final class sensor_msgs__msg__PointCloud__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__PointCloud> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsPointCloud extends BaseRosMessage<sensor_msgs__msg__PointCloud> {
  @override
  String get typeName => 'PointCloud';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsPointCloud() {
    data = calloc<sensor_msgs__msg__PointCloud>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'points' not generated;
  // reach the field directly via `data.ref.points`.
  // TODO(dart-gen): high-level accessor for 'channels' not generated;
  // reach the field directly via `data.ref.channels`.
}
