// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- sensor_msgs__msg__RegionOfInterest ----
base class sensor_msgs__msg__RegionOfInterest extends ffi.Struct {
  @ffi.Uint32()
  external int x_offset;
  @ffi.Uint32()
  external int y_offset;
  @ffi.Uint32()
  external int height;
  @ffi.Uint32()
  external int width;
  @ffi.Bool()
  external bool do_rectify;
}

final class sensor_msgs__msg__RegionOfInterest__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__RegionOfInterest> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsRegionOfInterest extends BaseRosMessage<sensor_msgs__msg__RegionOfInterest> {
  @override
  String get typeName => 'RegionOfInterest';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsRegionOfInterest() {
    data = calloc<sensor_msgs__msg__RegionOfInterest>();
  }

  int get xOffset =>
      data.ref.x_offset;
  set xOffset(int val) =>
      data.ref.x_offset = val;
  int get yOffset =>
      data.ref.y_offset;
  set yOffset(int val) =>
      data.ref.y_offset = val;
  int get height =>
      data.ref.height;
  set height(int val) =>
      data.ref.height = val;
  int get width =>
      data.ref.width;
  set width(int val) =>
      data.ref.width = val;
  bool get doRectify =>
      data.ref.do_rectify;
  set doRectify(bool val) =>
      data.ref.do_rectify = val;
}
