// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__RelativeHumidity ----
base class sensor_msgs__msg__RelativeHumidity extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Double()
  external double relative_humidity;
  @ffi.Double()
  external double variance;
}

final class sensor_msgs__msg__RelativeHumidity__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__RelativeHumidity> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsRelativeHumidity extends BaseRosMessage<sensor_msgs__msg__RelativeHumidity> {
  @override
  String get typeName => 'RelativeHumidity';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsRelativeHumidity() {
    data = calloc<sensor_msgs__msg__RelativeHumidity>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get relativeHumidity_ =>
      data.ref.relative_humidity;
  set relativeHumidity_(double val) =>
      data.ref.relative_humidity = val;
  double get variance =>
      data.ref.variance;
  set variance(double val) =>
      data.ref.variance = val;
}
