// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'camera_info.dart';

// ---- sensor_msgs__srv__SetCameraInfo_Request ----
base class sensor_msgs__srv__SetCameraInfo_Request extends ffi.Struct {
  external sensor_msgs__msg__CameraInfo camera_info;
}

final class sensor_msgs__srv__SetCameraInfo_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__srv__SetCameraInfo_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsSetCameraInfo_Request extends BaseRosMessage<sensor_msgs__srv__SetCameraInfo_Request> {
  @override
  String get typeName => 'SetCameraInfo_Request';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsSetCameraInfo_Request() {
    data = calloc<sensor_msgs__srv__SetCameraInfo_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'camera_info' not generated;
  // reach the field directly via `data.ref.camera_info`.
}

// ---- sensor_msgs__srv__SetCameraInfo_Response ----
base class sensor_msgs__srv__SetCameraInfo_Response extends ffi.Struct {
  @ffi.Bool()
  external bool success;
  external rosidl_runtime_c__String status_message;
}

final class sensor_msgs__srv__SetCameraInfo_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__srv__SetCameraInfo_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsSetCameraInfo_Response extends BaseRosMessage<sensor_msgs__srv__SetCameraInfo_Response> {
  @override
  String get typeName => 'SetCameraInfo_Response';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsSetCameraInfo_Response() {
    data = calloc<sensor_msgs__srv__SetCameraInfo_Response>();
    statusMessage = '';
  }

  bool get success =>
      data.ref.success;
  set success(bool val) =>
      data.ref.success = val;
  String get statusMessage {
    final s = data.ref.status_message;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set statusMessage(String val) {
    final b = val.toNativeUtf8();
    data.ref.status_message.data = b.cast<ffi.Char>();
    data.ref.status_message.size = b.length;
    data.ref.status_message.capacity = b.length + 1;
  }
}

// ---- SensorMsgsSetCameraInfo (service) ----
class SensorMsgsSetCameraInfo
    extends BaseRosService<SensorMsgsSetCameraInfo_Request, SensorMsgsSetCameraInfo_Response> {
  @override
  String get typeName => 'SetCameraInfo';
  @override
  String get packageName => 'sensor_msgs';

  @override
  SensorMsgsSetCameraInfo_Request createRequest() => SensorMsgsSetCameraInfo_Request();

  @override
  SensorMsgsSetCameraInfo_Response createResponse() => SensorMsgsSetCameraInfo_Response();
}
