// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- sensor_msgs__msg__Temperature ----
base class sensor_msgs__msg__Temperature extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Double()
  external double temperature;
  @ffi.Double()
  external double variance;
}

final class sensor_msgs__msg__Temperature__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__Temperature> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsTemperature extends BaseRosMessage<sensor_msgs__msg__Temperature> {
  @override
  String get typeName => 'Temperature';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsTemperature() {
    data = calloc<sensor_msgs__msg__Temperature>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get temperature_ =>
      data.ref.temperature;
  set temperature_(double val) =>
      data.ref.temperature = val;
  double get variance =>
      data.ref.variance;
  set variance(double val) =>
      data.ref.variance = val;
}
