// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- sensor_msgs__msg__TimeReference ----
base class sensor_msgs__msg__TimeReference extends ffi.Struct {
  external std_msgs__msg__Header header;
  external builtin_interfaces__msg__Time time_ref;
  external rosidl_runtime_c__String source;
}

final class sensor_msgs__msg__TimeReference__Sequence extends ffi.Struct {
  external ffi.Pointer<sensor_msgs__msg__TimeReference> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class SensorMsgsTimeReference extends BaseRosMessage<sensor_msgs__msg__TimeReference> {
  @override
  String get typeName => 'TimeReference';
  @override
  String get packageName => 'sensor_msgs';

  SensorMsgsTimeReference() {
    data = calloc<sensor_msgs__msg__TimeReference>();
    source = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'time_ref' not generated;
  // reach the field directly via `data.ref.time_ref`.
  String get source {
    final s = data.ref.source;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set source(String val) {
    final b = val.toNativeUtf8();
    data.ref.source.data = b.cast<ffi.Char>();
    data.ref.source.size = b.length;
    data.ref.source.capacity = b.length + 1;
  }
}
