// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'accel.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__AccelStamped ----
base class geometry_msgs__msg__AccelStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Accel accel;
}

final class geometry_msgs__msg__AccelStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__AccelStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsAccelStamped extends BaseRosMessage<geometry_msgs__msg__AccelStamped> {
  @override
  String get typeName => 'AccelStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsAccelStamped() {
    data = calloc<geometry_msgs__msg__AccelStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'accel' not generated;
  // reach the field directly via `data.ref.accel`.
}
