// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'accel_with_covariance.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__AccelWithCovarianceStamped ----
base class geometry_msgs__msg__AccelWithCovarianceStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__AccelWithCovariance accel;
}

final class geometry_msgs__msg__AccelWithCovarianceStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__AccelWithCovarianceStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsAccelWithCovarianceStamped extends BaseRosMessage<geometry_msgs__msg__AccelWithCovarianceStamped> {
  @override
  String get typeName => 'AccelWithCovarianceStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsAccelWithCovarianceStamped() {
    data = calloc<geometry_msgs__msg__AccelWithCovarianceStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'accel' not generated;
  // reach the field directly via `data.ref.accel`.
}
