// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'accel.dart';

// ---- geometry_msgs__msg__AccelWithCovariance ----
base class geometry_msgs__msg__AccelWithCovariance extends ffi.Struct {
  external geometry_msgs__msg__Accel accel;
  @ffi.Array(36)
  external ffi.Array<ffi.Double> covariance;
}

final class geometry_msgs__msg__AccelWithCovariance__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__AccelWithCovariance> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsAccelWithCovariance extends BaseRosMessage<geometry_msgs__msg__AccelWithCovariance> {
  @override
  String get typeName => 'AccelWithCovariance';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsAccelWithCovariance() {
    data = calloc<geometry_msgs__msg__AccelWithCovariance>();
  }

  // TODO(dart-gen): high-level accessor for 'accel' not generated;
  // reach the field directly via `data.ref.accel`.
  List<double> get covariance =>
      List.generate(36, (i) => data.ref.covariance[i]);
  set covariance(List<double> value) {
    for (var i = 0; i < 36 && i < value.length; i++) {
      data.ref.covariance[i] = value[i];
    }
  }
}
