// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'vector3.dart';

// ---- geometry_msgs__msg__Inertia ----
base class geometry_msgs__msg__Inertia extends ffi.Struct {
  @ffi.Double()
  external double m;
  external geometry_msgs__msg__Vector3 com;
  @ffi.Double()
  external double ixx;
  @ffi.Double()
  external double ixy;
  @ffi.Double()
  external double ixz;
  @ffi.Double()
  external double iyy;
  @ffi.Double()
  external double iyz;
  @ffi.Double()
  external double izz;
}

final class geometry_msgs__msg__Inertia__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Inertia> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsInertia extends BaseRosMessage<geometry_msgs__msg__Inertia> {
  @override
  String get typeName => 'Inertia';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsInertia() {
    data = calloc<geometry_msgs__msg__Inertia>();
  }

  double get m =>
      data.ref.m;
  set m(double val) =>
      data.ref.m = val;
  // TODO(dart-gen): high-level accessor for 'com' not generated;
  // reach the field directly via `data.ref.com`.
  double get ixx =>
      data.ref.ixx;
  set ixx(double val) =>
      data.ref.ixx = val;
  double get ixy =>
      data.ref.ixy;
  set ixy(double val) =>
      data.ref.ixy = val;
  double get ixz =>
      data.ref.ixz;
  set ixz(double val) =>
      data.ref.ixz = val;
  double get iyy =>
      data.ref.iyy;
  set iyy(double val) =>
      data.ref.iyy = val;
  double get iyz =>
      data.ref.iyz;
  set iyz(double val) =>
      data.ref.iyz = val;
  double get izz =>
      data.ref.izz;
  set izz(double val) =>
      data.ref.izz = val;
}
