// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'inertia.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__InertiaStamped ----
base class geometry_msgs__msg__InertiaStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Inertia inertia;
}

final class geometry_msgs__msg__InertiaStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__InertiaStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsInertiaStamped extends BaseRosMessage<geometry_msgs__msg__InertiaStamped> {
  @override
  String get typeName => 'InertiaStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsInertiaStamped() {
    data = calloc<geometry_msgs__msg__InertiaStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'inertia' not generated;
  // reach the field directly via `data.ref.inertia`.
}
