// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- geometry_msgs__msg__Point ----
base class geometry_msgs__msg__Point extends ffi.Struct {
  @ffi.Double()
  external double x;
  @ffi.Double()
  external double y;
  @ffi.Double()
  external double z;
}

final class geometry_msgs__msg__Point__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Point> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPoint extends BaseRosMessage<geometry_msgs__msg__Point> {
  @override
  String get typeName => 'Point';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPoint() {
    data = calloc<geometry_msgs__msg__Point>();
  }

  double get x =>
      data.ref.x;
  set x(double val) =>
      data.ref.x = val;
  double get y =>
      data.ref.y;
  set y(double val) =>
      data.ref.y = val;
  double get z =>
      data.ref.z;
  set z(double val) =>
      data.ref.z = val;
}
