// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'point.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PointStamped ----
base class geometry_msgs__msg__PointStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Point point;
}

final class geometry_msgs__msg__PointStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PointStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPointStamped extends BaseRosMessage<geometry_msgs__msg__PointStamped> {
  @override
  String get typeName => 'PointStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPointStamped() {
    data = calloc<geometry_msgs__msg__PointStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'point' not generated;
  // reach the field directly via `data.ref.point`.
}
