// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'polygon.dart';

// ---- geometry_msgs__msg__PolygonInstance ----
base class geometry_msgs__msg__PolygonInstance extends ffi.Struct {
  external geometry_msgs__msg__Polygon polygon;
  @ffi.Int64()
  external int id;
}

final class geometry_msgs__msg__PolygonInstance__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PolygonInstance> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPolygonInstance extends BaseRosMessage<geometry_msgs__msg__PolygonInstance> {
  @override
  String get typeName => 'PolygonInstance';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPolygonInstance() {
    data = calloc<geometry_msgs__msg__PolygonInstance>();
  }

  // TODO(dart-gen): high-level accessor for 'polygon' not generated;
  // reach the field directly via `data.ref.polygon`.
  int get id =>
      data.ref.id;
  set id(int val) =>
      data.ref.id = val;
}
