// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'polygon.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PolygonStamped ----
base class geometry_msgs__msg__PolygonStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Polygon polygon;
}

final class geometry_msgs__msg__PolygonStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PolygonStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPolygonStamped extends BaseRosMessage<geometry_msgs__msg__PolygonStamped> {
  @override
  String get typeName => 'PolygonStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPolygonStamped() {
    data = calloc<geometry_msgs__msg__PolygonStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'polygon' not generated;
  // reach the field directly via `data.ref.polygon`.
}
