// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'polygon_instance.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PolygonInstanceStamped ----
base class geometry_msgs__msg__PolygonInstanceStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__PolygonInstance polygon;
}

final class geometry_msgs__msg__PolygonInstanceStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PolygonInstanceStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPolygonInstanceStamped extends BaseRosMessage<geometry_msgs__msg__PolygonInstanceStamped> {
  @override
  String get typeName => 'PolygonInstanceStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPolygonInstanceStamped() {
    data = calloc<geometry_msgs__msg__PolygonInstanceStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'polygon' not generated;
  // reach the field directly via `data.ref.polygon`.
}
