// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'point32.dart';

// ---- geometry_msgs__msg__Polygon ----
base class geometry_msgs__msg__Polygon extends ffi.Struct {
  external geometry_msgs__msg__Point32__Sequence points;
}

final class geometry_msgs__msg__Polygon__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Polygon> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPolygon extends BaseRosMessage<geometry_msgs__msg__Polygon> {
  @override
  String get typeName => 'Polygon';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPolygon() {
    data = calloc<geometry_msgs__msg__Polygon>();
  }

  // TODO(dart-gen): high-level accessor for 'points' not generated;
  // reach the field directly via `data.ref.points`.
}
