// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'pose_with_covariance.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PoseWithCovarianceStamped ----
base class geometry_msgs__msg__PoseWithCovarianceStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__PoseWithCovariance pose;
}

final class geometry_msgs__msg__PoseWithCovarianceStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PoseWithCovarianceStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPoseWithCovarianceStamped extends BaseRosMessage<geometry_msgs__msg__PoseWithCovarianceStamped> {
  @override
  String get typeName => 'PoseWithCovarianceStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPoseWithCovarianceStamped() {
    data = calloc<geometry_msgs__msg__PoseWithCovarianceStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
}
