// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'pose.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PoseArray ----
base class geometry_msgs__msg__PoseArray extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Pose__Sequence poses;
}

final class geometry_msgs__msg__PoseArray__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PoseArray> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPoseArray extends BaseRosMessage<geometry_msgs__msg__PoseArray> {
  @override
  String get typeName => 'PoseArray';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPoseArray() {
    data = calloc<geometry_msgs__msg__PoseArray>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'poses' not generated;
  // reach the field directly via `data.ref.poses`.
}
