// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'point.dart';
import 'quaternion.dart';

// ---- geometry_msgs__msg__Pose ----
base class geometry_msgs__msg__Pose extends ffi.Struct {
  external geometry_msgs__msg__Point position;
  external geometry_msgs__msg__Quaternion orientation;
}

final class geometry_msgs__msg__Pose__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Pose> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPose extends BaseRosMessage<geometry_msgs__msg__Pose> {
  @override
  String get typeName => 'Pose';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPose() {
    data = calloc<geometry_msgs__msg__Pose>();
  }

  // TODO(dart-gen): high-level accessor for 'position' not generated;
  // reach the field directly via `data.ref.position`.
  // TODO(dart-gen): high-level accessor for 'orientation' not generated;
  // reach the field directly via `data.ref.orientation`.
}
