// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'pose.dart';

// ---- geometry_msgs__msg__PoseWithCovariance ----
base class geometry_msgs__msg__PoseWithCovariance extends ffi.Struct {
  external geometry_msgs__msg__Pose pose;
  @ffi.Array(36)
  external ffi.Array<ffi.Double> covariance;
}

final class geometry_msgs__msg__PoseWithCovariance__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PoseWithCovariance> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPoseWithCovariance extends BaseRosMessage<geometry_msgs__msg__PoseWithCovariance> {
  @override
  String get typeName => 'PoseWithCovariance';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPoseWithCovariance() {
    data = calloc<geometry_msgs__msg__PoseWithCovariance>();
  }

  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  List<double> get covariance =>
      List.generate(36, (i) => data.ref.covariance[i]);
  set covariance(List<double> value) {
    for (var i = 0; i < 36 && i < value.length; i++) {
      data.ref.covariance[i] = value[i];
    }
  }
}
