// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- geometry_msgs__msg__Pose2D ----
base class geometry_msgs__msg__Pose2D extends ffi.Struct {
  @ffi.Double()
  external double x;
  @ffi.Double()
  external double y;
  @ffi.Double()
  external double theta;
}

final class geometry_msgs__msg__Pose2D__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Pose2D> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPose2D extends BaseRosMessage<geometry_msgs__msg__Pose2D> {
  @override
  String get typeName => 'Pose2D';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPose2D() {
    data = calloc<geometry_msgs__msg__Pose2D>();
  }

  double get x =>
      data.ref.x;
  set x(double val) =>
      data.ref.x = val;
  double get y =>
      data.ref.y;
  set y(double val) =>
      data.ref.y = val;
  double get theta =>
      data.ref.theta;
  set theta(double val) =>
      data.ref.theta = val;
}
