// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'pose.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__PoseStamped ----
base class geometry_msgs__msg__PoseStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Pose pose;
}

final class geometry_msgs__msg__PoseStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__PoseStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsPoseStamped extends BaseRosMessage<geometry_msgs__msg__PoseStamped> {
  @override
  String get typeName => 'PoseStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsPoseStamped() {
    data = calloc<geometry_msgs__msg__PoseStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
}
