// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'quaternion.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__QuaternionStamped ----
base class geometry_msgs__msg__QuaternionStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Quaternion quaternion;
}

final class geometry_msgs__msg__QuaternionStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__QuaternionStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsQuaternionStamped extends BaseRosMessage<geometry_msgs__msg__QuaternionStamped> {
  @override
  String get typeName => 'QuaternionStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsQuaternionStamped() {
    data = calloc<geometry_msgs__msg__QuaternionStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'quaternion' not generated;
  // reach the field directly via `data.ref.quaternion`.
}
