// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- geometry_msgs__msg__Quaternion ----
base class geometry_msgs__msg__Quaternion extends ffi.Struct {
  @ffi.Double()
  external double x;
  @ffi.Double()
  external double y;
  @ffi.Double()
  external double z;
  @ffi.Double()
  external double w;
}

final class geometry_msgs__msg__Quaternion__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Quaternion> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsQuaternion extends BaseRosMessage<geometry_msgs__msg__Quaternion> {
  @override
  String get typeName => 'Quaternion';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsQuaternion() {
    data = calloc<geometry_msgs__msg__Quaternion>();
  }

  double get x =>
      data.ref.x;
  set x(double val) =>
      data.ref.x = val;
  double get y =>
      data.ref.y;
  set y(double val) =>
      data.ref.y = val;
  double get z =>
      data.ref.z;
  set z(double val) =>
      data.ref.z = val;
  double get w =>
      data.ref.w;
  set w(double val) =>
      data.ref.w = val;
}
