// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'quaternion.dart';
import 'vector3.dart';

// ---- geometry_msgs__msg__Transform ----
base class geometry_msgs__msg__Transform extends ffi.Struct {
  external geometry_msgs__msg__Vector3 translation;
  external geometry_msgs__msg__Quaternion rotation;
}

final class geometry_msgs__msg__Transform__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Transform> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTransform extends BaseRosMessage<geometry_msgs__msg__Transform> {
  @override
  String get typeName => 'Transform';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTransform() {
    data = calloc<geometry_msgs__msg__Transform>();
  }

  // TODO(dart-gen): high-level accessor for 'translation' not generated;
  // reach the field directly via `data.ref.translation`.
  // TODO(dart-gen): high-level accessor for 'rotation' not generated;
  // reach the field directly via `data.ref.rotation`.
}
