// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'transform.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- geometry_msgs__msg__TransformStamped ----
base class geometry_msgs__msg__TransformStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String child_frame_id;
  external geometry_msgs__msg__Transform transform;
}

final class geometry_msgs__msg__TransformStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__TransformStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTransformStamped extends BaseRosMessage<geometry_msgs__msg__TransformStamped> {
  @override
  String get typeName => 'TransformStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTransformStamped() {
    data = calloc<geometry_msgs__msg__TransformStamped>();
    childFrameId = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get childFrameId {
    final s = data.ref.child_frame_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set childFrameId(String val) {
    final b = val.toNativeUtf8();
    data.ref.child_frame_id.data = b.cast<ffi.Char>();
    data.ref.child_frame_id.size = b.length;
    data.ref.child_frame_id.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'transform' not generated;
  // reach the field directly via `data.ref.transform`.
}
