// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'twist_with_covariance.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__TwistWithCovarianceStamped ----
base class geometry_msgs__msg__TwistWithCovarianceStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__TwistWithCovariance twist;
}

final class geometry_msgs__msg__TwistWithCovarianceStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__TwistWithCovarianceStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTwistWithCovarianceStamped extends BaseRosMessage<geometry_msgs__msg__TwistWithCovarianceStamped> {
  @override
  String get typeName => 'TwistWithCovarianceStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTwistWithCovarianceStamped() {
    data = calloc<geometry_msgs__msg__TwistWithCovarianceStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'twist' not generated;
  // reach the field directly via `data.ref.twist`.
}
