// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'vector3.dart';

// ---- geometry_msgs__msg__Twist ----
base class geometry_msgs__msg__Twist extends ffi.Struct {
  external geometry_msgs__msg__Vector3 linear;
  external geometry_msgs__msg__Vector3 angular;
}

final class geometry_msgs__msg__Twist__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Twist> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTwist extends BaseRosMessage<geometry_msgs__msg__Twist> {
  @override
  String get typeName => 'Twist';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTwist() {
    data = calloc<geometry_msgs__msg__Twist>();
  }

  // TODO(dart-gen): high-level accessor for 'linear' not generated;
  // reach the field directly via `data.ref.linear`.
  // TODO(dart-gen): high-level accessor for 'angular' not generated;
  // reach the field directly via `data.ref.angular`.
}
