// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'twist.dart';

// ---- geometry_msgs__msg__TwistWithCovariance ----
base class geometry_msgs__msg__TwistWithCovariance extends ffi.Struct {
  external geometry_msgs__msg__Twist twist;
  @ffi.Array(36)
  external ffi.Array<ffi.Double> covariance;
}

final class geometry_msgs__msg__TwistWithCovariance__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__TwistWithCovariance> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTwistWithCovariance extends BaseRosMessage<geometry_msgs__msg__TwistWithCovariance> {
  @override
  String get typeName => 'TwistWithCovariance';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTwistWithCovariance() {
    data = calloc<geometry_msgs__msg__TwistWithCovariance>();
  }

  // TODO(dart-gen): high-level accessor for 'twist' not generated;
  // reach the field directly via `data.ref.twist`.
  List<double> get covariance =>
      List.generate(36, (i) => data.ref.covariance[i]);
  set covariance(List<double> value) {
    for (var i = 0; i < 36 && i < value.length; i++) {
      data.ref.covariance[i] = value[i];
    }
  }
}
