// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'twist.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__TwistStamped ----
base class geometry_msgs__msg__TwistStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Twist twist;
}

final class geometry_msgs__msg__TwistStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__TwistStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsTwistStamped extends BaseRosMessage<geometry_msgs__msg__TwistStamped> {
  @override
  String get typeName => 'TwistStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsTwistStamped() {
    data = calloc<geometry_msgs__msg__TwistStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'twist' not generated;
  // reach the field directly via `data.ref.twist`.
}
