// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'vector3.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__Vector3Stamped ----
base class geometry_msgs__msg__Vector3Stamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Vector3 vector;
}

final class geometry_msgs__msg__Vector3Stamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Vector3Stamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsVector3Stamped extends BaseRosMessage<geometry_msgs__msg__Vector3Stamped> {
  @override
  String get typeName => 'Vector3Stamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsVector3Stamped() {
    data = calloc<geometry_msgs__msg__Vector3Stamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'vector' not generated;
  // reach the field directly via `data.ref.vector`.
}
