// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'twist.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- geometry_msgs__msg__VelocityStamped ----
base class geometry_msgs__msg__VelocityStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String body_frame_id;
  external rosidl_runtime_c__String reference_frame_id;
  external geometry_msgs__msg__Twist velocity;
}

final class geometry_msgs__msg__VelocityStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__VelocityStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsVelocityStamped extends BaseRosMessage<geometry_msgs__msg__VelocityStamped> {
  @override
  String get typeName => 'VelocityStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsVelocityStamped() {
    data = calloc<geometry_msgs__msg__VelocityStamped>();
    bodyFrameId = '';
    referenceFrameId = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get bodyFrameId {
    final s = data.ref.body_frame_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set bodyFrameId(String val) {
    final b = val.toNativeUtf8();
    data.ref.body_frame_id.data = b.cast<ffi.Char>();
    data.ref.body_frame_id.size = b.length;
    data.ref.body_frame_id.capacity = b.length + 1;
  }
  String get referenceFrameId {
    final s = data.ref.reference_frame_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set referenceFrameId(String val) {
    final b = val.toNativeUtf8();
    data.ref.reference_frame_id.data = b.cast<ffi.Char>();
    data.ref.reference_frame_id.size = b.length;
    data.ref.reference_frame_id.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'velocity' not generated;
  // reach the field directly via `data.ref.velocity`.
}
