// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'wrench.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- geometry_msgs__msg__WrenchStamped ----
base class geometry_msgs__msg__WrenchStamped extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__Wrench wrench;
}

final class geometry_msgs__msg__WrenchStamped__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__WrenchStamped> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsWrenchStamped extends BaseRosMessage<geometry_msgs__msg__WrenchStamped> {
  @override
  String get typeName => 'WrenchStamped';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsWrenchStamped() {
    data = calloc<geometry_msgs__msg__WrenchStamped>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'wrench' not generated;
  // reach the field directly via `data.ref.wrench`.
}
