// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'vector3.dart';

// ---- geometry_msgs__msg__Wrench ----
base class geometry_msgs__msg__Wrench extends ffi.Struct {
  external geometry_msgs__msg__Vector3 force;
  external geometry_msgs__msg__Vector3 torque;
}

final class geometry_msgs__msg__Wrench__Sequence extends ffi.Struct {
  external ffi.Pointer<geometry_msgs__msg__Wrench> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class GeometryMsgsWrench extends BaseRosMessage<geometry_msgs__msg__Wrench> {
  @override
  String get typeName => 'Wrench';
  @override
  String get packageName => 'geometry_msgs';

  GeometryMsgsWrench() {
    data = calloc<geometry_msgs__msg__Wrench>();
  }

  // TODO(dart-gen): high-level accessor for 'force' not generated;
  // reach the field directly via `data.ref.force`.
  // TODO(dart-gen): high-level accessor for 'torque' not generated;
  // reach the field directly via `data.ref.torque`.
}
