// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- rcldart_msgs__srv__GetDistance_Request ----
base class rcldart_msgs__srv__GetDistance_Request extends ffi.Struct {
  external rosidl_runtime_c__String from_frame;
  external rosidl_runtime_c__String to_frame;
}

class RcldartMsgsGetDistance_Request extends BaseRosMessage<rcldart_msgs__srv__GetDistance_Request> {
  @override
  String get typeName => 'GetDistance_Request';
  @override
  String get packageName => 'rcldart_msgs';

  RcldartMsgsGetDistance_Request() {
    data = calloc<rcldart_msgs__srv__GetDistance_Request>();
    fromFrame = '';
    toFrame = '';
  }

  String get fromFrame {
    final s = data.ref.from_frame;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set fromFrame(String val) {
    final b = val.toNativeUtf8();
    data.ref.from_frame.data = b.cast<ffi.Char>();
    data.ref.from_frame.size = b.length;
    data.ref.from_frame.capacity = b.length + 1;
  }
  String get toFrame {
    final s = data.ref.to_frame;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set toFrame(String val) {
    final b = val.toNativeUtf8();
    data.ref.to_frame.data = b.cast<ffi.Char>();
    data.ref.to_frame.size = b.length;
    data.ref.to_frame.capacity = b.length + 1;
  }
}

// ---- rcldart_msgs__srv__GetDistance_Response ----
base class rcldart_msgs__srv__GetDistance_Response extends ffi.Struct {
  @ffi.Double()
  external double distance;
  @ffi.Bool()
  external bool success;
}

class RcldartMsgsGetDistance_Response extends BaseRosMessage<rcldart_msgs__srv__GetDistance_Response> {
  @override
  String get typeName => 'GetDistance_Response';
  @override
  String get packageName => 'rcldart_msgs';

  RcldartMsgsGetDistance_Response() {
    data = calloc<rcldart_msgs__srv__GetDistance_Response>();
  }

  double get distance =>
      data.ref.distance;
  set distance(double val) =>
      data.ref.distance = val;
  bool get success =>
      data.ref.success;
  set success(bool val) =>
      data.ref.success = val;
}

// ---- RcldartMsgsGetDistance (service) ----
class RcldartMsgsGetDistance
    extends BaseRosService<RcldartMsgsGetDistance_Request, RcldartMsgsGetDistance_Response> {
  @override
  String get typeName => 'GetDistance';
  @override
  String get packageName => 'rcldart_msgs';

  @override
  RcldartMsgsGetDistance_Request createRequest() => RcldartMsgsGetDistance_Request();

  @override
  RcldartMsgsGetDistance_Response createResponse() => RcldartMsgsGetDistance_Response();
}
