// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- rcldart_msgs__msg__RobotStatus ----
base class rcldart_msgs__msg__RobotStatus extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String robot_name;
  @ffi.Uint8()
  external int battery_percentage;
  @ffi.Bool()
  external bool is_charging;
  external rosidl_runtime_c__double__Sequence joint_positions;
}

class RcldartMsgsRobotStatus extends BaseRosMessage<rcldart_msgs__msg__RobotStatus> {
  @override
  String get typeName => 'RobotStatus';
  @override
  String get packageName => 'rcldart_msgs';

  RcldartMsgsRobotStatus() {
    data = calloc<rcldart_msgs__msg__RobotStatus>();
    robotName = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get robotName {
    final s = data.ref.robot_name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set robotName(String val) {
    final b = val.toNativeUtf8();
    data.ref.robot_name.data = b.cast<ffi.Char>();
    data.ref.robot_name.size = b.length;
    data.ref.robot_name.capacity = b.length + 1;
  }
  int get batteryPercentage =>
      data.ref.battery_percentage;
  set batteryPercentage(int val) =>
      data.ref.battery_percentage = val;
  bool get isCharging =>
      data.ref.is_charging;
  set isCharging(bool val) =>
      data.ref.is_charging = val;
  List<double> get jointPositions {
    final s = data.ref.joint_positions;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set jointPositions(List<double> value) {
    final a = calloc<ffi.Double>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.joint_positions.data = a;
    data.ref.joint_positions.size = value.length;
    data.ref.joint_positions.capacity = value.length;
  }
}
