// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- builtin_interfaces__msg__Duration ----
base class builtin_interfaces__msg__Duration extends ffi.Struct {
  @ffi.Int32()
  external int sec;
  @ffi.Uint32()
  external int nanosec;
}

final class builtin_interfaces__msg__Duration__Sequence extends ffi.Struct {
  external ffi.Pointer<builtin_interfaces__msg__Duration> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class BuiltinInterfacesDuration extends BaseRosMessage<builtin_interfaces__msg__Duration> {
  @override
  String get typeName => 'Duration';
  @override
  String get packageName => 'builtin_interfaces';

  BuiltinInterfacesDuration() {
    data = calloc<builtin_interfaces__msg__Duration>();
  }

  int get sec =>
      data.ref.sec;
  set sec(int val) =>
      data.ref.sec = val;
  int get nanosec =>
      data.ref.nanosec;
  set nanosec(int val) =>
      data.ref.nanosec = val;
}
