// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- builtin_interfaces__msg__Time ----
base class builtin_interfaces__msg__Time extends ffi.Struct {
  @ffi.Int32()
  external int sec;
  @ffi.Uint32()
  external int nanosec;
}

final class builtin_interfaces__msg__Time__Sequence extends ffi.Struct {
  external ffi.Pointer<builtin_interfaces__msg__Time> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class BuiltinInterfacesTime extends BaseRosMessage<builtin_interfaces__msg__Time> {
  @override
  String get typeName => 'Time';
  @override
  String get packageName => 'builtin_interfaces';

  BuiltinInterfacesTime() {
    data = calloc<builtin_interfaces__msg__Time>();
  }

  int get sec =>
      data.ref.sec;
  set sec(int val) =>
      data.ref.sec = val;
  int get nanosec =>
      data.ref.nanosec;
  set nanosec(int val) =>
      data.ref.nanosec = val;
}
