// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- diagnostic_msgs__srv__AddDiagnostics_Request ----
base class diagnostic_msgs__srv__AddDiagnostics_Request extends ffi.Struct {
  external rosidl_runtime_c__String load_namespace;
}

final class diagnostic_msgs__srv__AddDiagnostics_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__srv__AddDiagnostics_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsAddDiagnostics_Request extends BaseRosMessage<diagnostic_msgs__srv__AddDiagnostics_Request> {
  @override
  String get typeName => 'AddDiagnostics_Request';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsAddDiagnostics_Request() {
    data = calloc<diagnostic_msgs__srv__AddDiagnostics_Request>();
    loadNamespace = '';
  }

  String get loadNamespace {
    final s = data.ref.load_namespace;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set loadNamespace(String val) {
    final b = val.toNativeUtf8();
    data.ref.load_namespace.data = b.cast<ffi.Char>();
    data.ref.load_namespace.size = b.length;
    data.ref.load_namespace.capacity = b.length + 1;
  }
}

// ---- diagnostic_msgs__srv__AddDiagnostics_Response ----
base class diagnostic_msgs__srv__AddDiagnostics_Response extends ffi.Struct {
  @ffi.Bool()
  external bool success;
  external rosidl_runtime_c__String message;
}

final class diagnostic_msgs__srv__AddDiagnostics_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__srv__AddDiagnostics_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsAddDiagnostics_Response extends BaseRosMessage<diagnostic_msgs__srv__AddDiagnostics_Response> {
  @override
  String get typeName => 'AddDiagnostics_Response';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsAddDiagnostics_Response() {
    data = calloc<diagnostic_msgs__srv__AddDiagnostics_Response>();
    message = '';
  }

  bool get success =>
      data.ref.success;
  set success(bool val) =>
      data.ref.success = val;
  String get message {
    final s = data.ref.message;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set message(String val) {
    final b = val.toNativeUtf8();
    data.ref.message.data = b.cast<ffi.Char>();
    data.ref.message.size = b.length;
    data.ref.message.capacity = b.length + 1;
  }
}

// ---- DiagnosticMsgsAddDiagnostics (service) ----
class DiagnosticMsgsAddDiagnostics
    extends BaseRosService<DiagnosticMsgsAddDiagnostics_Request, DiagnosticMsgsAddDiagnostics_Response> {
  @override
  String get typeName => 'AddDiagnostics';
  @override
  String get packageName => 'diagnostic_msgs';

  @override
  DiagnosticMsgsAddDiagnostics_Request createRequest() => DiagnosticMsgsAddDiagnostics_Request();

  @override
  DiagnosticMsgsAddDiagnostics_Response createResponse() => DiagnosticMsgsAddDiagnostics_Response();
}
