// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'key_value.dart';

// ---- diagnostic_msgs__msg__DiagnosticStatus ----
base class diagnostic_msgs__msg__DiagnosticStatus extends ffi.Struct {
  @ffi.Uint8()
  external int level;
  external rosidl_runtime_c__String name;
  external rosidl_runtime_c__String message;
  external rosidl_runtime_c__String hardware_id;
  external diagnostic_msgs__msg__KeyValue__Sequence values;
}

final class diagnostic_msgs__msg__DiagnosticStatus__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__msg__DiagnosticStatus> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsDiagnosticStatus extends BaseRosMessage<diagnostic_msgs__msg__DiagnosticStatus> {
  @override
  String get typeName => 'DiagnosticStatus';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsDiagnosticStatus() {
    data = calloc<diagnostic_msgs__msg__DiagnosticStatus>();
    name = '';
    message = '';
    hardwareId = '';
  }

  static const int OK =
      0;
  static const int WARN =
      1;
  static const int ERROR =
      2;
  static const int STALE =
      3;
  int get level =>
      data.ref.level;
  set level(int val) =>
      data.ref.level = val;
  String get name {
    final s = data.ref.name;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set name(String val) {
    final b = val.toNativeUtf8();
    data.ref.name.data = b.cast<ffi.Char>();
    data.ref.name.size = b.length;
    data.ref.name.capacity = b.length + 1;
  }
  String get message {
    final s = data.ref.message;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set message(String val) {
    final b = val.toNativeUtf8();
    data.ref.message.data = b.cast<ffi.Char>();
    data.ref.message.size = b.length;
    data.ref.message.capacity = b.length + 1;
  }
  String get hardwareId {
    final s = data.ref.hardware_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set hardwareId(String val) {
    final b = val.toNativeUtf8();
    data.ref.hardware_id.data = b.cast<ffi.Char>();
    data.ref.hardware_id.size = b.length;
    data.ref.hardware_id.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'values' not generated;
  // reach the field directly via `data.ref.values`.
}
