// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'diagnostic_status.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- diagnostic_msgs__msg__DiagnosticArray ----
base class diagnostic_msgs__msg__DiagnosticArray extends ffi.Struct {
  external std_msgs__msg__Header header;
  external diagnostic_msgs__msg__DiagnosticStatus__Sequence status;
}

final class diagnostic_msgs__msg__DiagnosticArray__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__msg__DiagnosticArray> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsDiagnosticArray extends BaseRosMessage<diagnostic_msgs__msg__DiagnosticArray> {
  @override
  String get typeName => 'DiagnosticArray';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsDiagnosticArray() {
    data = calloc<diagnostic_msgs__msg__DiagnosticArray>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'status' not generated;
  // reach the field directly via `data.ref.status`.
}
