// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- diagnostic_msgs__msg__KeyValue ----
base class diagnostic_msgs__msg__KeyValue extends ffi.Struct {
  external rosidl_runtime_c__String key;
  external rosidl_runtime_c__String value;
}

final class diagnostic_msgs__msg__KeyValue__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__msg__KeyValue> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsKeyValue extends BaseRosMessage<diagnostic_msgs__msg__KeyValue> {
  @override
  String get typeName => 'KeyValue';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsKeyValue() {
    data = calloc<diagnostic_msgs__msg__KeyValue>();
    key = '';
    value = '';
  }

  String get key {
    final s = data.ref.key;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set key(String val) {
    final b = val.toNativeUtf8();
    data.ref.key.data = b.cast<ffi.Char>();
    data.ref.key.size = b.length;
    data.ref.key.capacity = b.length + 1;
  }
  String get value {
    final s = data.ref.value;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set value(String val) {
    final b = val.toNativeUtf8();
    data.ref.value.data = b.cast<ffi.Char>();
    data.ref.value.size = b.length;
    data.ref.value.capacity = b.length + 1;
  }
}
