// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'diagnostic_status.dart';

// ---- diagnostic_msgs__srv__SelfTest_Request ----
base class diagnostic_msgs__srv__SelfTest_Request extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class diagnostic_msgs__srv__SelfTest_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__srv__SelfTest_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsSelfTest_Request extends BaseRosMessage<diagnostic_msgs__srv__SelfTest_Request> {
  @override
  String get typeName => 'SelfTest_Request';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsSelfTest_Request() {
    data = calloc<diagnostic_msgs__srv__SelfTest_Request>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}

// ---- diagnostic_msgs__srv__SelfTest_Response ----
base class diagnostic_msgs__srv__SelfTest_Response extends ffi.Struct {
  external rosidl_runtime_c__String id;
  @ffi.Uint8()
  external int passed;
  external diagnostic_msgs__msg__DiagnosticStatus__Sequence status;
}

final class diagnostic_msgs__srv__SelfTest_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<diagnostic_msgs__srv__SelfTest_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class DiagnosticMsgsSelfTest_Response extends BaseRosMessage<diagnostic_msgs__srv__SelfTest_Response> {
  @override
  String get typeName => 'SelfTest_Response';
  @override
  String get packageName => 'diagnostic_msgs';

  DiagnosticMsgsSelfTest_Response() {
    data = calloc<diagnostic_msgs__srv__SelfTest_Response>();
    id = '';
  }

  String get id {
    final s = data.ref.id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set id(String val) {
    final b = val.toNativeUtf8();
    data.ref.id.data = b.cast<ffi.Char>();
    data.ref.id.size = b.length;
    data.ref.id.capacity = b.length + 1;
  }
  int get passed =>
      data.ref.passed;
  set passed(int val) =>
      data.ref.passed = val;
  // TODO(dart-gen): high-level accessor for 'status' not generated;
  // reach the field directly via `data.ref.status`.
}

// ---- DiagnosticMsgsSelfTest (service) ----
class DiagnosticMsgsSelfTest
    extends BaseRosService<DiagnosticMsgsSelfTest_Request, DiagnosticMsgsSelfTest_Response> {
  @override
  String get typeName => 'SelfTest';
  @override
  String get packageName => 'diagnostic_msgs';

  @override
  DiagnosticMsgsSelfTest_Request createRequest() => DiagnosticMsgsSelfTest_Request();

  @override
  DiagnosticMsgsSelfTest_Response createResponse() => DiagnosticMsgsSelfTest_Response();
}
