// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Bool ----
base class std_msgs__msg__Bool extends ffi.Struct {
  @ffi.Bool()
  external bool data;
}

final class std_msgs__msg__Bool__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Bool> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsBool extends BaseRosMessage<std_msgs__msg__Bool> {
  @override
  String get typeName => 'Bool';

  StdMsgsBool() {
    data = calloc<std_msgs__msg__Bool>();
  }

  bool get value =>
      data.ref.data;
  set value(bool val) =>
      data.ref.data = val;
}
