// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Byte ----
base class std_msgs__msg__Byte extends ffi.Struct {
  @ffi.Uint8()
  external int data;
}

final class std_msgs__msg__Byte__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Byte> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsByte extends BaseRosMessage<std_msgs__msg__Byte> {
  @override
  String get typeName => 'Byte';

  StdMsgsByte() {
    data = calloc<std_msgs__msg__Byte>();
  }

  int get value =>
      data.ref.data;
  set value(int val) =>
      data.ref.data = val;
}
