// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Char ----
base class std_msgs__msg__Char extends ffi.Struct {
  @ffi.Uint8()
  external int data;
}

final class std_msgs__msg__Char__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Char> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsChar extends BaseRosMessage<std_msgs__msg__Char> {
  @override
  String get typeName => 'Char';

  StdMsgsChar() {
    data = calloc<std_msgs__msg__Char>();
  }

  int get value =>
      data.ref.data;
  set value(int val) =>
      data.ref.data = val;
}
