// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__ColorRGBA ----
base class std_msgs__msg__ColorRGBA extends ffi.Struct {
  @ffi.Float()
  external double r;
  @ffi.Float()
  external double g;
  @ffi.Float()
  external double b;
  @ffi.Float()
  external double a;
}

final class std_msgs__msg__ColorRGBA__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__ColorRGBA> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsColorRGBA extends BaseRosMessage<std_msgs__msg__ColorRGBA> {
  @override
  String get typeName => 'ColorRGBA';

  StdMsgsColorRGBA() {
    data = calloc<std_msgs__msg__ColorRGBA>();
  }

  double get r =>
      data.ref.r;
  set r(double val) =>
      data.ref.r = val;
  double get g =>
      data.ref.g;
  set g(double val) =>
      data.ref.g = val;
  double get b =>
      data.ref.b;
  set b(double val) =>
      data.ref.b = val;
  double get a =>
      data.ref.a;
  set a(double val) =>
      data.ref.a = val;
}
