// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Empty ----
base class std_msgs__msg__Empty extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class std_msgs__msg__Empty__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Empty> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsEmpty extends BaseRosMessage<std_msgs__msg__Empty> {
  @override
  String get typeName => 'Empty';

  StdMsgsEmpty() {
    data = calloc<std_msgs__msg__Empty>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}
