// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'multi_array_layout.dart';

// ---- std_msgs__msg__Float32MultiArray ----
base class std_msgs__msg__Float32MultiArray extends ffi.Struct {
  external std_msgs__msg__MultiArrayLayout layout;
  external rosidl_runtime_c__float__Sequence data;
}

final class std_msgs__msg__Float32MultiArray__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Float32MultiArray> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsFloat32MultiArray extends BaseRosMessage<std_msgs__msg__Float32MultiArray> {
  @override
  String get typeName => 'Float32MultiArray';

  StdMsgsFloat32MultiArray() {
    data = calloc<std_msgs__msg__Float32MultiArray>();
  }

  // TODO(dart-gen): high-level accessor for 'layout' not generated;
  // reach the field directly via `data.ref.layout`.
  List<double> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<double> value) {
    final a = calloc<ffi.Float>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
}
