// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Float64 ----
base class std_msgs__msg__Float64 extends ffi.Struct {
  @ffi.Double()
  external double data;
}

final class std_msgs__msg__Float64__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Float64> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsFloat64 extends BaseRosMessage<std_msgs__msg__Float64> {
  @override
  String get typeName => 'Float64';

  StdMsgsFloat64() {
    data = calloc<std_msgs__msg__Float64>();
  }

  double get value =>
      data.ref.data;
  set value(double val) =>
      data.ref.data = val;
}
