// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Float32 ----
base class std_msgs__msg__Float32 extends ffi.Struct {
  @ffi.Float()
  external double data;
}

final class std_msgs__msg__Float32__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Float32> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsFloat32 extends BaseRosMessage<std_msgs__msg__Float32> {
  @override
  String get typeName => 'Float32';

  StdMsgsFloat32() {
    data = calloc<std_msgs__msg__Float32>();
  }

  double get value =>
      data.ref.data;
  set value(double val) =>
      data.ref.data = val;
}
