// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart' hide rosidl_runtime_c__String;

// ---- std_msgs__msg__Header ----
base class std_msgs__msg__Header extends ffi.Struct {
  external builtin_interfaces__msg__Time stamp;
  external rosidl_runtime_c__String frame_id;
}

final class std_msgs__msg__Header__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Header> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsHeader extends BaseRosMessage<std_msgs__msg__Header> {
  @override
  String get typeName => 'Header';

  StdMsgsHeader() {
    data = calloc<std_msgs__msg__Header>();
    frameId = '';
  }

  // TODO(dart-gen): high-level accessor for 'stamp' not generated;
  // reach the field directly via `data.ref.stamp`.
  String get frameId {
    final s = data.ref.frame_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set frameId(String val) {
    final b = val.toNativeUtf8();
    data.ref.frame_id.data = b.cast<ffi.Char>();
    data.ref.frame_id.size = b.length;
    data.ref.frame_id.capacity = b.length + 1;
  }
}
