// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Int16 ----
base class std_msgs__msg__Int16 extends ffi.Struct {
  @ffi.Int16()
  external int data;
}

final class std_msgs__msg__Int16__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Int16> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsInt16 extends BaseRosMessage<std_msgs__msg__Int16> {
  @override
  String get typeName => 'Int16';

  StdMsgsInt16() {
    data = calloc<std_msgs__msg__Int16>();
  }

  int get value =>
      data.ref.data;
  set value(int val) =>
      data.ref.data = val;
}
