// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__Int8 ----
base class std_msgs__msg__Int8 extends ffi.Struct {
  @ffi.Int8()
  external int data;
}

final class std_msgs__msg__Int8__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__Int8> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsInt8 extends BaseRosMessage<std_msgs__msg__Int8> {
  @override
  String get typeName => 'Int8';

  StdMsgsInt8() {
    data = calloc<std_msgs__msg__Int8>();
  }

  int get value =>
      data.ref.data;
  set value(int val) =>
      data.ref.data = val;
}
