// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- std_msgs__msg__MultiArrayDimension ----
base class std_msgs__msg__MultiArrayDimension extends ffi.Struct {
  external rosidl_runtime_c__String label;
  @ffi.Uint32()
  external int size;
  @ffi.Uint32()
  external int stride;
}

final class std_msgs__msg__MultiArrayDimension__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__MultiArrayDimension> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsMultiArrayDimension extends BaseRosMessage<std_msgs__msg__MultiArrayDimension> {
  @override
  String get typeName => 'MultiArrayDimension';

  StdMsgsMultiArrayDimension() {
    data = calloc<std_msgs__msg__MultiArrayDimension>();
    label = '';
  }

  String get label {
    final s = data.ref.label;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set label(String val) {
    final b = val.toNativeUtf8();
    data.ref.label.data = b.cast<ffi.Char>();
    data.ref.label.size = b.length;
    data.ref.label.capacity = b.length + 1;
  }
  int get size =>
      data.ref.size;
  set size(int val) =>
      data.ref.size = val;
  int get stride =>
      data.ref.stride;
  set stride(int val) =>
      data.ref.stride = val;
}
