// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'multi_array_dimension.dart';

// ---- std_msgs__msg__MultiArrayLayout ----
base class std_msgs__msg__MultiArrayLayout extends ffi.Struct {
  external std_msgs__msg__MultiArrayDimension__Sequence dim;
  @ffi.Uint32()
  external int data_offset;
}

final class std_msgs__msg__MultiArrayLayout__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__MultiArrayLayout> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsMultiArrayLayout extends BaseRosMessage<std_msgs__msg__MultiArrayLayout> {
  @override
  String get typeName => 'MultiArrayLayout';

  StdMsgsMultiArrayLayout() {
    data = calloc<std_msgs__msg__MultiArrayLayout>();
  }

  // TODO(dart-gen): high-level accessor for 'dim' not generated;
  // reach the field directly via `data.ref.dim`.
  int get dataOffset =>
      data.ref.data_offset;
  set dataOffset(int val) =>
      data.ref.data_offset = val;
}
