// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';

// ---- std_msgs__msg__String ----
base class std_msgs__msg__String extends ffi.Struct {
  external rosidl_runtime_c__String data;
}

final class std_msgs__msg__String__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__String> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsString extends BaseRosMessage<std_msgs__msg__String> {
  @override
  String get typeName => 'String';

  StdMsgsString() {
    data = calloc<std_msgs__msg__String>();
    value = '';
  }

  String get value {
    final s = data.ref.data;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set value(String val) {
    final b = val.toNativeUtf8();
    data.ref.data.data = b.cast<ffi.Char>();
    data.ref.data.size = b.length;
    data.ref.data.capacity = b.length + 1;
  }
}
