// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';

// ---- std_msgs__msg__UInt32 ----
base class std_msgs__msg__UInt32 extends ffi.Struct {
  @ffi.Uint32()
  external int data;
}

final class std_msgs__msg__UInt32__Sequence extends ffi.Struct {
  external ffi.Pointer<std_msgs__msg__UInt32> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class StdMsgsUInt32 extends BaseRosMessage<std_msgs__msg__UInt32> {
  @override
  String get typeName => 'UInt32';

  StdMsgsUInt32() {
    data = calloc<std_msgs__msg__UInt32>();
  }

  int get value =>
      data.ref.data;
  set value(int val) =>
      data.ref.data = val;
}
