// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'occupancy_grid.dart';

// ---- nav_msgs__srv__GetMap_Request ----
base class nav_msgs__srv__GetMap_Request extends ffi.Struct {
  @ffi.Uint8()
  external int structure_needs_at_least_one_member;
}

final class nav_msgs__srv__GetMap_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__GetMap_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsGetMap_Request extends BaseRosMessage<nav_msgs__srv__GetMap_Request> {
  @override
  String get typeName => 'GetMap_Request';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsGetMap_Request() {
    data = calloc<nav_msgs__srv__GetMap_Request>();
  }

  int get structureNeedsAtLeastOneMember =>
      data.ref.structure_needs_at_least_one_member;
  set structureNeedsAtLeastOneMember(int val) =>
      data.ref.structure_needs_at_least_one_member = val;
}

// ---- nav_msgs__srv__GetMap_Response ----
base class nav_msgs__srv__GetMap_Response extends ffi.Struct {
  external nav_msgs__msg__OccupancyGrid map;
}

final class nav_msgs__srv__GetMap_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__GetMap_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsGetMap_Response extends BaseRosMessage<nav_msgs__srv__GetMap_Response> {
  @override
  String get typeName => 'GetMap_Response';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsGetMap_Response() {
    data = calloc<nav_msgs__srv__GetMap_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'map' not generated;
  // reach the field directly via `data.ref.map`.
}

// ---- NavMsgsGetMap (service) ----
class NavMsgsGetMap
    extends BaseRosService<NavMsgsGetMap_Request, NavMsgsGetMap_Response> {
  @override
  String get typeName => 'GetMap';
  @override
  String get packageName => 'nav_msgs';

  @override
  NavMsgsGetMap_Request createRequest() => NavMsgsGetMap_Request();

  @override
  NavMsgsGetMap_Response createResponse() => NavMsgsGetMap_Response();
}
