// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'path.dart';
import 'package:geometry_msgs/geometry_msgs.dart';

// ---- nav_msgs__srv__GetPlan_Request ----
base class nav_msgs__srv__GetPlan_Request extends ffi.Struct {
  external geometry_msgs__msg__PoseStamped start;
  external geometry_msgs__msg__PoseStamped goal;
  @ffi.Float()
  external double tolerance;
}

final class nav_msgs__srv__GetPlan_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__GetPlan_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsGetPlan_Request extends BaseRosMessage<nav_msgs__srv__GetPlan_Request> {
  @override
  String get typeName => 'GetPlan_Request';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsGetPlan_Request() {
    data = calloc<nav_msgs__srv__GetPlan_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'start' not generated;
  // reach the field directly via `data.ref.start`.
  // TODO(dart-gen): high-level accessor for 'goal' not generated;
  // reach the field directly via `data.ref.goal`.
  double get tolerance =>
      data.ref.tolerance;
  set tolerance(double val) =>
      data.ref.tolerance = val;
}

// ---- nav_msgs__srv__GetPlan_Response ----
base class nav_msgs__srv__GetPlan_Response extends ffi.Struct {
  external nav_msgs__msg__Path plan;
}

final class nav_msgs__srv__GetPlan_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__GetPlan_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsGetPlan_Response extends BaseRosMessage<nav_msgs__srv__GetPlan_Response> {
  @override
  String get typeName => 'GetPlan_Response';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsGetPlan_Response() {
    data = calloc<nav_msgs__srv__GetPlan_Response>();
  }

  // TODO(dart-gen): high-level accessor for 'plan' not generated;
  // reach the field directly via `data.ref.plan`.
}

// ---- NavMsgsGetPlan (service) ----
class NavMsgsGetPlan
    extends BaseRosService<NavMsgsGetPlan_Request, NavMsgsGetPlan_Response> {
  @override
  String get typeName => 'GetPlan';
  @override
  String get packageName => 'nav_msgs';

  @override
  NavMsgsGetPlan_Request createRequest() => NavMsgsGetPlan_Request();

  @override
  NavMsgsGetPlan_Response createResponse() => NavMsgsGetPlan_Response();
}
