// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:geometry_msgs/geometry_msgs.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- nav_msgs__msg__GridCells ----
base class nav_msgs__msg__GridCells extends ffi.Struct {
  external std_msgs__msg__Header header;
  @ffi.Float()
  external double cell_width;
  @ffi.Float()
  external double cell_height;
  external geometry_msgs__msg__Point__Sequence cells;
}

final class nav_msgs__msg__GridCells__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__msg__GridCells> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsGridCells extends BaseRosMessage<nav_msgs__msg__GridCells> {
  @override
  String get typeName => 'GridCells';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsGridCells() {
    data = calloc<nav_msgs__msg__GridCells>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  double get cellWidth =>
      data.ref.cell_width;
  set cellWidth(double val) =>
      data.ref.cell_width = val;
  double get cellHeight =>
      data.ref.cell_height;
  set cellHeight(double val) =>
      data.ref.cell_height = val;
  // TODO(dart-gen): high-level accessor for 'cells' not generated;
  // reach the field directly via `data.ref.cells`.
}
