// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'occupancy_grid.dart';

// ---- nav_msgs__srv__LoadMap_Request ----
base class nav_msgs__srv__LoadMap_Request extends ffi.Struct {
  external rosidl_runtime_c__String map_url;
}

final class nav_msgs__srv__LoadMap_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__LoadMap_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsLoadMap_Request extends BaseRosMessage<nav_msgs__srv__LoadMap_Request> {
  @override
  String get typeName => 'LoadMap_Request';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsLoadMap_Request() {
    data = calloc<nav_msgs__srv__LoadMap_Request>();
    mapUrl = '';
  }

  String get mapUrl {
    final s = data.ref.map_url;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set mapUrl(String val) {
    final b = val.toNativeUtf8();
    data.ref.map_url.data = b.cast<ffi.Char>();
    data.ref.map_url.size = b.length;
    data.ref.map_url.capacity = b.length + 1;
  }
}

// ---- nav_msgs__srv__LoadMap_Response ----
base class nav_msgs__srv__LoadMap_Response extends ffi.Struct {
  external nav_msgs__msg__OccupancyGrid map;
  @ffi.Uint8()
  external int result;
}

final class nav_msgs__srv__LoadMap_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__LoadMap_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsLoadMap_Response extends BaseRosMessage<nav_msgs__srv__LoadMap_Response> {
  @override
  String get typeName => 'LoadMap_Response';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsLoadMap_Response() {
    data = calloc<nav_msgs__srv__LoadMap_Response>();
  }

  static const int RESULT_SUCCESS =
      0;
  static const int RESULT_MAP_DOES_NOT_EXIST =
      1;
  static const int RESULT_INVALID_MAP_DATA =
      2;
  static const int RESULT_INVALID_MAP_METADATA =
      3;
  static const int RESULT_UNDEFINED_FAILURE =
      255;
  // TODO(dart-gen): high-level accessor for 'map' not generated;
  // reach the field directly via `data.ref.map`.
  int get result =>
      data.ref.result;
  set result(int val) =>
      data.ref.result = val;
}

// ---- NavMsgsLoadMap (service) ----
class NavMsgsLoadMap
    extends BaseRosService<NavMsgsLoadMap_Request, NavMsgsLoadMap_Response> {
  @override
  String get typeName => 'LoadMap';
  @override
  String get packageName => 'nav_msgs';

  @override
  NavMsgsLoadMap_Request createRequest() => NavMsgsLoadMap_Request();

  @override
  NavMsgsLoadMap_Response createResponse() => NavMsgsLoadMap_Response();
}
