// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:builtin_interfaces/builtin_interfaces.dart';
import 'package:geometry_msgs/geometry_msgs.dart';

// ---- nav_msgs__msg__MapMetaData ----
base class nav_msgs__msg__MapMetaData extends ffi.Struct {
  external builtin_interfaces__msg__Time map_load_time;
  @ffi.Float()
  external double resolution;
  @ffi.Uint32()
  external int width;
  @ffi.Uint32()
  external int height;
  external geometry_msgs__msg__Pose origin;
}

final class nav_msgs__msg__MapMetaData__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__msg__MapMetaData> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsMapMetaData extends BaseRosMessage<nav_msgs__msg__MapMetaData> {
  @override
  String get typeName => 'MapMetaData';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsMapMetaData() {
    data = calloc<nav_msgs__msg__MapMetaData>();
  }

  // TODO(dart-gen): high-level accessor for 'map_load_time' not generated;
  // reach the field directly via `data.ref.map_load_time`.
  double get resolution =>
      data.ref.resolution;
  set resolution(double val) =>
      data.ref.resolution = val;
  int get width =>
      data.ref.width;
  set width(int val) =>
      data.ref.width = val;
  int get height =>
      data.ref.height;
  set height(int val) =>
      data.ref.height = val;
  // TODO(dart-gen): high-level accessor for 'origin' not generated;
  // reach the field directly via `data.ref.origin`.
}
