// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'map_meta_data.dart';
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- nav_msgs__msg__OccupancyGrid ----
base class nav_msgs__msg__OccupancyGrid extends ffi.Struct {
  external std_msgs__msg__Header header;
  external nav_msgs__msg__MapMetaData info;
  external rosidl_runtime_c__int8__Sequence data;
}

final class nav_msgs__msg__OccupancyGrid__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__msg__OccupancyGrid> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsOccupancyGrid extends BaseRosMessage<nav_msgs__msg__OccupancyGrid> {
  @override
  String get typeName => 'OccupancyGrid';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsOccupancyGrid() {
    data = calloc<nav_msgs__msg__OccupancyGrid>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'info' not generated;
  // reach the field directly via `data.ref.info`.
  List<int> get value {
    final s = data.ref.data;
    return List.generate(s.size, (i) => s.data[i]);
  }
  set value(List<int> value) {
    final a = calloc<ffi.Int8>(value.length);
    for (var i = 0; i < value.length; i++) {
      a[i] = value[i];
    }
    data.ref.data.data = a;
    data.ref.data.size = value.length;
    data.ref.data.capacity = value.length;
  }
}
