// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import '_rosidl_types.dart';
import 'package:geometry_msgs/geometry_msgs.dart' hide rosidl_runtime_c__String;
import 'package:std_msgs/std_msgs.dart' hide rosidl_runtime_c__String;

// ---- nav_msgs__msg__Odometry ----
base class nav_msgs__msg__Odometry extends ffi.Struct {
  external std_msgs__msg__Header header;
  external rosidl_runtime_c__String child_frame_id;
  external geometry_msgs__msg__PoseWithCovariance pose;
  external geometry_msgs__msg__TwistWithCovariance twist;
}

final class nav_msgs__msg__Odometry__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__msg__Odometry> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsOdometry extends BaseRosMessage<nav_msgs__msg__Odometry> {
  @override
  String get typeName => 'Odometry';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsOdometry() {
    data = calloc<nav_msgs__msg__Odometry>();
    childFrameId = '';
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  String get childFrameId {
    final s = data.ref.child_frame_id;
    if (s.data == ffi.nullptr || s.size == 0) return '';
    return s.data.cast<Utf8>().toDartString(length: s.size);
  }
  set childFrameId(String val) {
    final b = val.toNativeUtf8();
    data.ref.child_frame_id.data = b.cast<ffi.Char>();
    data.ref.child_frame_id.size = b.length;
    data.ref.child_frame_id.capacity = b.length + 1;
  }
  // TODO(dart-gen): high-level accessor for 'pose' not generated;
  // reach the field directly via `data.ref.pose`.
  // TODO(dart-gen): high-level accessor for 'twist' not generated;
  // reach the field directly via `data.ref.twist`.
}
