// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'package:geometry_msgs/geometry_msgs.dart';
import 'package:std_msgs/std_msgs.dart';

// ---- nav_msgs__msg__Path ----
base class nav_msgs__msg__Path extends ffi.Struct {
  external std_msgs__msg__Header header;
  external geometry_msgs__msg__PoseStamped__Sequence poses;
}

final class nav_msgs__msg__Path__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__msg__Path> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsPath extends BaseRosMessage<nav_msgs__msg__Path> {
  @override
  String get typeName => 'Path';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsPath() {
    data = calloc<nav_msgs__msg__Path>();
  }

  // TODO(dart-gen): high-level accessor for 'header' not generated;
  // reach the field directly via `data.ref.header`.
  // TODO(dart-gen): high-level accessor for 'poses' not generated;
  // reach the field directly via `data.ref.poses`.
}
