// generated by rosidl_generator_dart (gen_dart_package)
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:rcldart_utils/rcldart_utils.dart';
import 'occupancy_grid.dart';
import 'package:geometry_msgs/geometry_msgs.dart';

// ---- nav_msgs__srv__SetMap_Request ----
base class nav_msgs__srv__SetMap_Request extends ffi.Struct {
  external nav_msgs__msg__OccupancyGrid map;
  external geometry_msgs__msg__PoseWithCovarianceStamped initial_pose;
}

final class nav_msgs__srv__SetMap_Request__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__SetMap_Request> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsSetMap_Request extends BaseRosMessage<nav_msgs__srv__SetMap_Request> {
  @override
  String get typeName => 'SetMap_Request';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsSetMap_Request() {
    data = calloc<nav_msgs__srv__SetMap_Request>();
  }

  // TODO(dart-gen): high-level accessor for 'map' not generated;
  // reach the field directly via `data.ref.map`.
  // TODO(dart-gen): high-level accessor for 'initial_pose' not generated;
  // reach the field directly via `data.ref.initial_pose`.
}

// ---- nav_msgs__srv__SetMap_Response ----
base class nav_msgs__srv__SetMap_Response extends ffi.Struct {
  @ffi.Bool()
  external bool success;
}

final class nav_msgs__srv__SetMap_Response__Sequence extends ffi.Struct {
  external ffi.Pointer<nav_msgs__srv__SetMap_Response> data;
  @ffi.Size()
  external int size;
  @ffi.Size()
  external int capacity;
}
class NavMsgsSetMap_Response extends BaseRosMessage<nav_msgs__srv__SetMap_Response> {
  @override
  String get typeName => 'SetMap_Response';
  @override
  String get packageName => 'nav_msgs';

  NavMsgsSetMap_Response() {
    data = calloc<nav_msgs__srv__SetMap_Response>();
  }

  bool get success =>
      data.ref.success;
  set success(bool val) =>
      data.ref.success = val;
}

// ---- NavMsgsSetMap (service) ----
class NavMsgsSetMap
    extends BaseRosService<NavMsgsSetMap_Request, NavMsgsSetMap_Response> {
  @override
  String get typeName => 'SetMap';
  @override
  String get packageName => 'nav_msgs';

  @override
  NavMsgsSetMap_Request createRequest() => NavMsgsSetMap_Request();

  @override
  NavMsgsSetMap_Response createResponse() => NavMsgsSetMap_Response();
}
